/* Base curada do portfólio Albert Gil.
 * Fontes: apresentações de resultados (.pptx) e planilhas consolidadas (.xlsx) da pasta
 * "Resultados Consultoria". Valores em R$ são ganhos líquidos anuais declarados pelas empresas
 * ao fim de cada programa. `p:true` marca valor projetado e `x:true` valor ainda a validar (ambos ficam
 * fora das somas). `semTotal` indica programa cujo relatório não traz o ganho de todas as empresas.
 * Ficaram de fora por estarem fora de escala e sem confirmação: Satis (R$ 42 mi, Araxá) e
 * Destilaria Veredas (R$ 162 mi, Patos de Minas). "Apresentação - Lean 2015" é duplicata de
 * "Apresentação - Lean" e o deck BH/CL repete a turma dos slides 78-100 dele.
 */
window.AG_SECTORS = {
  ind: "Indústria",
  ofi: "Reparação automotiva",
  ali: "Alimentos",
  con: "Construção civil",
  ser: "Comércio e serviços",
  pub: "Gestão pública",
};

window.AG_PROGRAMS = [
  {
    id: "lean-automotivo", semTotal: true,
    nome: "Lean Automotivo",
    ano: 2009, anoLabel: "2009–2014",
    parceiro: "Cadeia automotiva · fornecedores 1º e 2º tier",
    local: "Minas Gerais e São Paulo",
    cidades: ["Betim", "Belo Horizonte", "Santo André"],
    setores: ["ind"],
    e: 311,
    resumo: "Seis edições com fornecedores da cadeia automotiva, de 9 a 55 empresas por turma. Cerca de mil participantes e 500 projetos Kaizen implementados em ciclos de 4 a 5 meses.",
    kpis: [["311", "empresas"], ["~1.000", "participantes"], ["~500", "projetos implementados"]],
    empresas: [
      { n: "OMR", s: "Autopeças · linha de volantes", g: 1500000, bc: 285.03, r: "−80% de estoque e WIP, 75% de área recuperada" },
      { n: "BorgWarner", s: "Autopeças", g: 1124280, bc: 329, r: "−86% de estoque em processo" },
      { n: "Denso Sistemas Térmicos", s: "Autopeças", bc: 86.23, r: "16% da mão de obra realocada, −505 min de parada" },
      { n: "Stola do Brasil", s: "Autopeças", r: "+340% de produtividade, NVAA de 71% para 39%, payback em 4 meses" },
    ],
    fotos: [],
  },
  {
    id: "focem-abdi",
    nome: "Adensamento produtivo Mercosul",
    ano: 2012, anoLabel: "2012",
    parceiro: "FOCEM · ABDI · MDIC",
    local: "Grande ABC (SP) e Serra Gaúcha (RS)",
    cidades: ["Santo André", "Caxias do Sul", "São Leopoldo"],
    setores: ["ind"],
    e: 44,
    resumo: "Projeto federal de adensamento de cadeias do Mercosul com 25 empresas paulistas e 19 gaúchas, todas do setor metalmecânico e de autopeças.",
    kpis: [["−55,8%", "NVAA médio"], ["+40,2%", "peças por hora"], ["−78,5%", "tempo de set-up"], ["+33,1%", "OEE"]],
    empresas: [
      { n: "Metaldavi", s: "Metalmecânico · Caxias do Sul", r: "Lote de 600 dobradiças de 10 dias para 3,9 horas (−95,8%), produção puxada" },
      { n: "Inpel Transmissões Mecânicas", s: "Metalmecânico · São Leopoldo", r: "−46,15% no custo de produção, validado pela controladoria" },
    ],
    fotos: ["metaldavi-linha", "inpel-celula"],
  },
  {
    id: "bh-lafaiete-2014",
    nome: "Academia Lean · BH e Conselheiro Lafaiete",
    ano: 2014, anoLabel: "2014",
    parceiro: "SEBRAE Minas",
    local: "Grande BH e Conselheiro Lafaiete (MG)",
    cidades: ["Belo Horizonte", "Conselheiro Lafaiete"],
    setores: ["ind", "ser"],
    e: 19,
    gTotal: 1659727, gNota: "19 empresas × ganho líquido médio de R$ 87,4 mil",
    resumo: "De junho a novembro de 2014, mais de 680 horas de treinamento e consultoria no chão de fábrica de 12 empresas da Grande BH e 7 de Conselheiro Lafaiete.",
    kpis: [["+110%", "produtividade média"], ["−60,1%", "NVAA médio"], ["−61,3%", "deslocamento"], ["−41,7%", "horas extras"]],
    empresas: [
      { n: "Soma Usinagem e Caldeiraria", s: "Usinagem · Conselheiro Lafaiete", g: 250000, r: "+350% de produtividade no centro de usinagem, preço final 57% menor" },
      { n: "Delta Usinagem", s: "Usinagem · BH", r: "−95% de NVAA no centro de usinagem" },
      { n: "Suporte Automação Industrial", s: "Automação · BH", bc: 112.03, r: "Cada R$ 1 investido retornou R$ 112" },
      { n: "Visual Propaganda", s: "Comunicação visual · BH", r: "−69% de deslocamento e mais de 110 m² liberados" },
      { n: "HB Locações", s: "Locação", g: 160000, r: "Ganho líquido acima de R$ 160 mil" },
      { n: "CompIT", s: "Assistência técnica em TI", r: "+125% de performance" },
      { n: "Dedetizar", s: "Serviços · BH", r: "−50% de horas extras com balanceamento de atividades" },
      { n: "Dablius Industrial", s: "Indústria · Conselheiro Lafaiete", r: "Pátio de sobras reorganizado e estoque controlado" },
      { n: "Causimec", s: "Usinagem", r: "Ferramentaria padronizada e layout do torno revisto" },
      { n: "Isotec", s: "Instrumentos de medição", r: "Bancada de calibração redesenhada" },
      { n: "Balanças Precisa", s: "Metrologia", r: "Corredor de produção liberado e demarcado" },
    ],
    fotos: ["visual-fachada", "visual-galpao", "dablius-patio", "isotec-bancada", "precisa-oficina", "causimec-ferramentaria", "compit-bancada", "suporte-bancada", "visual-corredor", "visual-recepcao", "visual-patio"],
  },
  {
    id: "oficinas-2015",
    nome: "Lean na Reparação Automotiva",
    ano: 2015, anoLabel: "2015",
    parceiro: "SEBRAE Minas",
    local: "Belo Horizonte (MG)",
    cidades: ["Belo Horizonte"],
    setores: ["ofi"],
    e: 11,
    resumo: "Onze oficinas mecânicas de BH aplicaram organização do posto de trabalho, cronoanálise e balanceamento para liberar mais veículos por dia com a mesma equipe.",
    kpis: [["−96%", "deslocamento interno (melhor caso)"], ["+25%", "veículos entregues (melhor caso)"], ["3.960 h", "ociosas eliminadas por ano"]],
    empresas: [
      { n: "Carrera", g: 1118282, bc: 179.64, r: "−96% de NVAA de deslocamento, +17% de produtividade (264 veículos/ano), 3.960 h ociosas a menos" },
      { n: "Autorom", g: 681911, bc: 420, r: "+25% de produtividade (180 veículos/ano), 1.440 h ociosas a menos" },
      { n: "Mecânica Gilmar", g: 462000, bc: 49, r: "−96% de NVAA, 3 profissionais realocados" },
      { n: "Montanha", g: 189222, bc: 72.2, r: "−27% de NVAA" },
      { n: "Motorplan", g: 172000, bc: 9.75, r: "−95% de NVAA, 2.640 h ociosas a menos" },
      { n: "Kadosh", g: 112707, bc: 70.2, r: "3 profissionais realocados" },
      { n: "Mecalazo", g: 111153, bc: 67.8, r: "−88% de NVAA, +12,5% de produtividade" },
      { n: "Moraes", g: 109000, bc: 68.2, r: "+10% de produtividade, horas extras zeradas" },
      { n: "Chekcar", g: 85108, bc: 53.3, r: "3 profissionais realocados" },
      { n: "Cafcar", g: 71424, bc: 44.9, r: "+12% de produtividade com um profissional a menos" },
      { n: "Pachauto", g: 10372, bc: 7.37, r: "130 m² de espaço ocioso recuperado" },
    ],
    fotos: [],
  },
  {
    id: "friburgo-2015", semTotal: true,
    nome: "Academia Lean · Nova Friburgo",
    ano: 2015, anoLabel: "2015",
    parceiro: "SEBRAE Rio",
    local: "Nova Friburgo (RJ)",
    cidades: ["Nova Friburgo"],
    setores: ["ind", "ali", "ser"],
    e: 14,
    resumo: "Catorze empresas de oito setores, do polo de moda íntima a fechaduras, injeção plástica e farmácia de manipulação. Cerca de 73 pessoas capacitadas.",
    kpis: [["3,4×", "produção do corte (Ryjor)"], ["−85,4%", "set-up de injetoras"], ["−96%", "falhas de equipamento (Haga)"]],
    empresas: [
      { n: "Ryjor Underwear", s: "Moda íntima", g: 83200, r: "Corte de 5.577 para 19.186 peças/mês, −95% de retrabalho" },
      { n: "Haga Fechaduras", s: "Fechaduras e ferragens", r: "Falhas de equipamento de 110 para 4 ocorrências" },
      { n: "Hela Fechaduras", s: "Fechaduras e ferragens", r: "Até +98% de produtividade na linha de vidro" },
      { n: "Sistal", s: "Segurança eletrônica", r: "+30% de produtividade na manutenção (meta era 10%)" },
      { n: "Fórmula Exata", s: "Farmácia de manipulação", r: "+25% de produtividade, +11,5% de faturamento" },
      { n: "Massa da Serra", s: "Alimentos", r: "+13% no cozimento, +24% de área de atendimento" },
      { n: "Lucitex Lingerie", s: "Moda íntima", r: "Padronização da confecção e redução de NVAA" },
    ],
    fotos: [],
  },
  {
    id: "monlevade-2015", semTotal: true,
    nome: "Programa Lean · João Monlevade",
    ano: 2015, anoLabel: "2015",
    parceiro: "SEBRAE · Regional Rio Doce",
    local: "João Monlevade (MG)",
    cidades: ["João Monlevade"],
    setores: ["ind", "ali", "ser"],
    e: 13,
    resumo: "Treze empresas do vale do aço, de caldeirarias que atendem a siderurgia a uma fábrica de pão de queijo. Quatro meses de projeto, de agosto a novembro.",
    kpis: [["460 m²", "liberados na Metaltécnica"], ["28 t", "de sucata vendidas"], ["86%", "nota 5S na JW (meta 80%)"]],
    empresas: [
      { n: "Metaltécnica", s: "Caldeiraria e usinagem", g: 975238, bc: 16.77, r: "Solda de 40 m para 5 m do almoxarifado, −60% a −87% de movimentação" },
      { n: "Qualictec", s: "Mecânica industrial", r: "−40% de horas perdidas com spaghetti chart e 5S" },
      { n: "JW Manutenções", s: "Manutenção de talhas", g: 97582, bc: 25.72, r: "−78% de deslocamento, 88 m² liberados, arquivos 100% padronizados" },
      { n: "Rancho de Minas", s: "Pão de queijo e biscoitos", g: 3403626, bc: 40.98, p: true, r: "−79% de retrabalho no corte, capacidade de congelamento triplicada" },
      { n: "Festas Práticas", s: "Locação para eventos", r: "+59% de performance na loja, −20% de avarias" },
    ],
    fotos: ["metaltecnica-almox", "metaltecnica-producao", "jw-almox", "qualictec-galpao", "qualictec-ponte"],
  },
  {
    id: "uba",
    nome: "Programa Lean · Ubá",
    ano: 2015, anoLabel: "2015",
    parceiro: "SEBRAE Minas",
    local: "Ubá (MG)",
    cidades: ["Ubá"],
    setores: ["ind", "ali", "ser"],
    e: 12,
    gTotal: 1351000, gNota: "total consolidado do grupo",
    resumo: "Polo moveleiro e de confecção da Zona da Mata. Doze empresas, de panificadora a gráfica e fábrica de uniformes.",
    kpis: [["−72%", "deslocamento médio"], ["−65%", "NVAA em set-up e paradas"], ["+79%", "performance média da função"]],
    empresas: [
      { n: "Panificadora Só Delícias" }, { n: "HM Uniformes" }, { n: "Gráfica Seculus" }, { n: "LJ Móveis" },
      { n: "Glaucelar" }, { n: "Ferkyt" }, { n: "Jacar" }, { n: "Certa" }, { n: "Klaus" }, { n: "Mundo Azul" }, { n: "Avanzi" }, { n: "Oficina Plástico" },
    ],
    fotos: [],
  },
  {
    id: "petropolis",
    nome: "Programa Lean · Petrópolis",
    ano: 2016, anoLabel: "2016",
    parceiro: "SEBRAE Rio",
    local: "Petrópolis (RJ)",
    cidades: ["Petrópolis"],
    setores: ["ind", "ali", "ser"],
    e: 9,
    resumo: "Nove empresas da serra fluminense. É o programa com o maior ganho total da carteira, puxado por três empresas acima de R$ 2 milhões por ano.",
    kpis: [["R$ 10,9 mi", "ganho líquido anual"], ["222×", "melhor benefício/custo"], ["−95%", "retrabalho (Thiamo)"]],
    empresas: [
      { n: "Pássaro Livre", g: 3448651, bc: 154, r: "−50% de horas ociosas, +36% de produtividade, −56% de estoque" },
      { n: "MM Plastic", g: 2376677, bc: 191, r: "−50% de NVAA, 5 pessoas realocadas, −89% de estoque" },
      { n: "Oficina 16", g: 2317403, bc: 222, r: "−60% de estoque, 19 pessoas realocadas" },
      { n: "Graças Torradas", s: "Alimentos", g: 957103, bc: 214, r: "−83% de absenteísmo, −58% de estoque" },
      { n: "Vizoo", g: 710719, bc: 33.5, r: "+30% de produtividade, 56% da produção internalizada" },
      { n: "Sinal Publicidade", g: 398257, bc: 41.7, r: "−72% de NVAA, +25% de produtividade" },
      { n: "Incisor", g: 270954, bc: 12.6, r: "−95% de NVAA, +57% de produtividade" },
      { n: "Thiamo", g: 255794, bc: 19.2, r: "−95% de retrabalho" },
      { n: "Kappauns", g: 194354, bc: 9.85, r: "Produtividade dobrada, −67% de retrabalho" },
    ],
    fotos: [],
  },
  {
    id: "volta-redonda",
    nome: "Programa Lean · Volta Redonda",
    ano: 2017, anoLabel: "2017",
    parceiro: "SEBRAE Rio",
    local: "Volta Redonda (RJ)",
    cidades: ["Volta Redonda"],
    setores: ["ind", "ali", "ser", "con"],
    e: 10,
    resumo: "Dez empresas do Médio Paraíba, de olaria e laticínio a hortifrúti, engenharia e guindastes.",
    kpis: [["R$ 4,2 mi", "ganho líquido anual"], ["−81%", "deslocamento (Graal)"], ["−80%", "estoque (Olaria)"]],
    empresas: [
      { n: "Resen Munck", g: 1028923, r: "−29% de horas extras, +36% de faturamento" },
      { n: "Graal Embaixador", g: 784000, r: "−81% de deslocamento, start-up de loja em metade do tempo" },
      { n: "VR Horti Fruti", g: 754000, r: "−70% de deslocamento, −60% de custos diretos" },
      { n: "Inspire-se", g: 566000, r: "+91% de crescimento do negócio" },
      { n: "Olaria São Sebastião", g: 522000, r: "−80% de estoque, +10% de produtividade" },
      { n: "KVG Engenharia", g: 240000, r: "−35% de horas ociosas, −20% de custos diretos" },
      { n: "Vó Alzira", s: "Alimentos", g: 109000, r: "−30% de deslocamento, 35% da mão de obra otimizada" },
      { n: "Dental Karisma", g: 102000, r: "30% da mão de obra otimizada" },
      { n: "Laticínios Clarice", s: "Alimentos", g: 66400, r: "+30% de performance, −10% de custos diretos" },
      { n: "Rede Construir" },
    ],
    fotos: [],
  },
  {
    id: "rio-2017",
    nome: "Programa Lean · Rio e Baixada Fluminense",
    ano: 2017, anoLabel: "2017",
    parceiro: "SEBRAE Rio",
    local: "Rio de Janeiro e Baixada Fluminense (RJ)",
    cidades: ["Rio de Janeiro", "Duque de Caxias"],
    setores: ["ind", "ser"],
    e: 6,
    resumo: "Seis empresas entre indústria, logística, locação e varejo. Onze postos de trabalho realocados para atividades que agregam valor.",
    kpis: [["R$ 4,5 mi", "ganho líquido anual"], ["−95%", "deslocamento (Espirodutos)"], ["400 m²", "liberados (JA Logística)"]],
    empresas: [
      { n: "Nova Peças", g: 2099616, r: "+10% de ticket médio, 2 pessoas realocadas" },
      { n: "Espirodutos", g: 1020000, r: "−95% de deslocamento, 8 pessoas realocadas" },
      { n: "Alfatec", s: "Refrigeração industrial", g: 809000, r: "−61% de deslocamento, OEE de 77,2% na montagem" },
      { n: "Violeta Skate Rock", g: 398000, r: "−25% de estoque, −50% de custos diretos" },
      { n: "PTA Rental", g: 120000, r: "Performance da função 2,2× maior" },
      { n: "JA Logística", g: 49200, r: "400 m² liberados e estoque sob controle" },
    ],
    fotos: [],
  },
  {
    id: "sete-lagoas-2017",
    nome: "Programa Lean · Sete Lagoas",
    ano: 2017, anoLabel: "2017",
    parceiro: "SEBRAE Minas",
    local: "Sete Lagoas (MG)",
    cidades: ["Sete Lagoas"],
    setores: ["ind", "ser"],
    e: 6,
    resumo: "Seis empresas da região central de Minas, com destaque para uma fabricante de equipamentos que cortou 80% dos custos diretos do processo.",
    kpis: [["R$ 2,4 mi", "ganho líquido anual"], ["−80%", "custos diretos (Hystermaq)"], ["+71%", "crescimento (Prática)"]],
    empresas: [
      { n: "Hystermaq", g: 1347850, r: "−80% de custos diretos, +34% de produtividade" },
      { n: "Prática Consultoria", g: 410000, r: "+71% de crescimento do negócio" },
      { n: "Lubrifrança", g: 206000, r: "−84% de deslocamento e de NVAA em set-up" },
      { n: "Teyte Modas", g: 180000, r: "−37,5% de estoque" },
      { n: "Central da Economia", g: 135000, r: "Performance da função dobrada, estoque sob controle" },
      { n: "Traço Comunicação", g: 78000, r: "26% da mão de obra otimizada" },
    ],
    fotos: [],
  },
  {
    id: "procompi-2017",
    nome: "PROCOMPI · Alto Paranaíba e Triângulo",
    ano: 2017, anoLabel: "2017",
    parceiro: "PROCOMPI · FIEMG · SEBRAE",
    local: "Patos de Minas e Triângulo Mineiro (MG)",
    cidades: ["Patos de Minas"],
    setores: ["ind", "ali", "con"],
    e: 5,
    resumo: "Cinco empresas e 229 oportunidades de melhoria mapeadas, de uma fábrica de bolsas a um laticínio de queijo coalho e uma obra de edifício-sede.",
    kpis: [["831×", "benefício/custo (Julev)"], ["−31,7%", "perda de queijo (Tirolez)"], ["229", "oportunidades mapeadas"]],
    empresas: [
      { n: "Julev Bolsas", g: 1570000, bc: 831, r: "+100% de produtividade em bolsas, +42% em carteiras, −90% de NVAA" },
      { n: "Levfort", g: 1200000, bc: 808, r: "−73% de NVAA, +15% de produtividade" },
      { n: "Bota Brasil", g: 561000, bc: 40.5, r: "−50% de horas ociosas, −50% de horas extras da liderança" },
      { n: "Tirolez · Tiros", s: "Laticínios", g: 82698, bc: 11.2, r: "−31,7% de perda de massa, −62,5% de homem-hora na embalagem" },
      { n: "Tetum Engenharia", s: "Construção · obra Sicoob Credicopa", r: "+60% de performance com 5S e controles de obra" },
    ],
    fotos: ["tetum-obra"],
  },
  {
    id: "iel-triangulo-2017",
    nome: "IEL PCIR · Araxá, Patos e Uberlândia",
    ano: 2017, anoLabel: "2017",
    parceiro: "IEL · FIEMG",
    local: "Araxá, Patos de Minas e Uberlândia (MG)",
    cidades: ["Araxá", "Patos de Minas", "Uberlândia"],
    setores: ["ind", "ali", "ser"],
    e: 13,
    resumo: "Programa de competitividade industrial regional do IEL com indústrias de fertilizantes, alimentos, destilarias e serviços.",
    kpis: [["−99%", "refugo (Santa Clara)"], ["−90%", "retrabalho (Ducks)"], ["−96%", "deslocamento (Sol e Ondas)"]],
    empresas: [
      { n: "Santa Clara", s: "Araxá", g: 6725160, x: true, r: "−99,1% de refugo, +85% de produtividade" },
      { n: "Fertitrading", s: "Fertilizantes · Araxá", g: 1910000, r: "−50% de deslocamento, +20% de produtividade" },
      { n: "Marabá", s: "Patos de Minas", g: 1120000, r: "−83% de deslocamento, 2 pessoas realocadas" },
      { n: "Sol e Ondas", s: "Patos de Minas", g: 810000, r: "−96% de deslocamento, +50% de produtividade" },
      { n: "Serya", s: "Araxá", g: 481000, r: "−80% de horas extras, −47% de custos diretos" },
      { n: "PDCA", s: "Uberlândia", g: 219972, r: "−90% de horas extras" },
      { n: "Flexcon", s: "Patos de Minas", g: 48000, r: "−50% de custos diretos" },
      { n: "Destilaria Rio do Cachimbo", s: "Patos de Minas", g: 42000, r: "5S em 77% e 90 m² liberados" },
      { n: "Ducks", s: "Patos de Minas", r: "−90% de retrabalho" },
    ],
    fotos: [],
  },
  {
    id: "lean-construction-2018",
    nome: "Lean Construction · Uberlândia e Uberaba",
    ano: 2018, anoLabel: "2017–2018",
    parceiro: "PROCOMPI · FIEMG",
    local: "Uberlândia e Uberaba (MG)",
    cidades: ["Uberlândia", "Uberaba"],
    setores: ["con"],
    e: 16,
    resumo: "Dezesseis construtoras e incorporadoras levaram o Lean ao canteiro, de novembro de 2017 a maio de 2018: estudo de passos, controle de almoxarifado, traço de argamassa e cronograma.",
    kpis: [["−97%", "deslocamento no canteiro (Pittelli)"], ["57% → 0%", "desvio de estoque (HPR)"], ["4 meses", "de antecipação de obra (Dakarsa)"]],
    empresas: [
      { n: "Cincol Construtora", g: 1340000, r: "−30% de mão de obra direta, +20% de produtividade em alvenaria e reboco" },
      { n: "TCENCO", g: 1139400, r: "−15% de custos diretos, 40% da mão de obra otimizada" },
      { n: "RCG", g: 236000, r: "−80% de deslocamento na confecção de lajes, −34% de ociosidade" },
      { n: "HPR Construtora", g: 164000, r: "Desvio de estoque de 57% para 0%, −78% em locação de máquinas" },
      { n: "Pittelli Engenharia", g: 75300, r: "Container de cimento ao lado da betoneira: de 39 passos para 1 por viagem" },
      { n: "Nunes e Nunes", r: "−44% de argamassa, −33% de matéria-prima" },
      { n: "Canassa", r: "−53,6% de atraso de obra" },
      { n: "Dakarsa", r: "Obra entregue 4 meses antes do previsto" },
      { n: "Ribeiro e Ribeiro", r: "+44% de vendas" },
    ],
    fotos: [],
  },
  {
    id: "refrigeracao-2018",
    nome: "Lean na Refrigeração",
    ano: 2018, anoLabel: "2018",
    parceiro: "SEBRAE",
    local: "Setor de refrigeração e climatização",
    cidades: [],
    setores: ["ser"],
    e: 2,
    resumo: "Turma setorial com empresas de instalação e manutenção de refrigeração.",
    kpis: [["−84%", "NVAA em set-up (Apolo)"], ["+60%", "faturamento (Reclimar)"]],
    empresas: [
      { n: "Apolo", g: 263000, r: "−84% de NVAA em set-up e paradas, −50% de horas ociosas" },
      { n: "Reclimar", g: 96294, r: "+60% de faturamento" },
    ],
    fotos: [],
  },
  {
    id: "itajuba-2019",
    nome: "PROCOMPI · Itajubá",
    ano: 2019, anoLabel: "2018–2019",
    parceiro: "PROCOMPI · FIEMG · SIMMMEI",
    local: "Itajubá, Sul de Minas (MG)",
    cidades: ["Itajubá"],
    setores: ["ind"],
    e: 5,
    resumo: "Ferramentarias e usinagens do Sul de Minas, de julho de 2018 a fevereiro de 2019. Uma delas desenvolveu um software de programação CNC no conceito Indústria 4.0.",
    kpis: [["−80%", "set-up do torno CNC (RCS)"], ["+60%", "OEE (RCS)"], ["2.780 h", "de máquina liberadas por ano"]],
    empresas: [
      { n: "GIMA Máquinas", g: 1440178, r: "+80% de OEE, −43% de NVAA, 100% de reaproveitamento do estoque" },
      { n: "RCS Usinagem", bc: 104.45, r: "Programação + set-up de 3,5 h para 45 min, refugo de try-out zerado" },
      { n: "Erominas", g: 630000, p: true, r: "+30% de produtividade e de disponibilidade de máquina" },
      { n: "GNS", r: "Deslocamento de 532 para 260 m/dia, NVAA de 73% para 45%" },
      { n: "Invent Automação", r: "+30% de produtividade, −30% de set-up" },
    ],
    fotos: ["rcs-ferramentas", "rcs-bancada"],
  },
  {
    id: "patos-2019",
    nome: "PROCOMPI · Patos de Minas",
    ano: 2019, anoLabel: "2019",
    parceiro: "PROCOMPI · FIEMG",
    local: "Patos de Minas (MG)",
    cidades: ["Patos de Minas"],
    setores: ["ind", "ofi"],
    e: 14,
    resumo: "Catorze empresas do Alto Paranaíba, metade delas oficinas de caminhões e distribuidoras de peças. Na maioria, o payback veio em menos de um mês.",
    kpis: [["R$ 13 mi", "ganho líquido anual"], ["521×", "benefício/custo (Volksdiesel)"], ["< 1 mês", "payback em 10 de 11 empresas"]],
    empresas: [
      { n: "Oficina do Baiano", s: "Reparação de veículos pesados", g: 3359960, bc: 178, r: "+150% de produtividade" },
      { n: "Aço Fort", g: 3099400, bc: 14.1, r: "Produtividade dobrada, −85% de NVAA" },
      { n: "Trucks Hélio", g: 2050000, bc: 70.2, r: "−50% de NVAA e de horas extras" },
      { n: "Diferpam", g: 1005600, bc: 32.3, r: "+85% de performance, +36% de produtividade" },
      { n: "Motocarga", g: 797664, bc: 122, r: "−90% de NVAA, +42% de produtividade" },
      { n: "Volksdiesel", g: 675000, bc: 521, r: "−85% de NVAA, +44% de produtividade, −50% de horas extras" },
      { n: "Dicave · JD Peças", g: 632973, bc: 37, r: "−75% de NVAA" },
      { n: "Reformas Vieira", g: 599000, r: "−50% de estoque" },
      { n: "Aço Fama", g: 304500, bc: 5.95, r: "−90% de NVAA, +62% de produtividade, payback em 2 meses" },
      { n: "Trucks Alair", g: 249000, bc: 250, r: "Estoque reorganizado e 5S implantado" },
      { n: "Dante Molas", g: 230300, bc: 24.7, r: "−20% de estoque" },
      { n: "Acinox" }, { n: "Empa" }, { n: "Recalto" },
    ],
    fotos: [],
  },
  {
    id: "multibag-2024",
    nome: "Consultoria direta · Multibag",
    ano: 2024, anoLabel: "2024",
    parceiro: "Cliente privado",
    local: "Indústria de big bags",
    cidades: [],
    setores: ["ind"],
    e: 1,
    resumo: "Acompanhamento mensal de indicadores com a diretoria: produção, absenteísmo, eficiência e planejamento.",
    kpis: [["+18%", "produção média diária"], ["+17,6%", "faturamento médio mensal"], ["2,5 → <1", "mês de planejamento"]],
    empresas: [{ n: "Multibag", r: "Produção diária 18% maior que em 2023, planejamento de 2,5 meses para menos de um" }],
    fotos: [],
  },
];

/* Outros trabalhos citados nas apresentações, sem números consolidados. */
window.AG_OTHERS = [
  { nome: "Prefeitura de Betim · Programa Cesta Escola", setor: "pub", cidade: "Betim", nota: "Lean na gestão pública: descentralização do atendimento para reduzir a espera dos beneficiários." },
  { nome: "Lean Garage Pernambuco", setor: "ofi", cidade: "Recife", nota: "Programa de melhoria contínua para oficinas em Pernambuco." },
  { nome: "Reparação automotiva · ES e RJ", setor: "ofi", cidade: "Cariacica", nota: "Oficinas em Cariacica, Cachoeiro de Itapemirim e Duque de Caxias." },
];

/* Pares de antes e depois, todos com o mesmo recorte e o mesmo tratamento. */
window.AG_PAIRS = {
  "visual-fachada": { emp: "Visual Propaganda", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Fachada e recepção", txt: "A empresa saiu do improviso e ganhou uma entrada que conta o que ela faz.", kpi: "−69% de deslocamento" },
  "visual-galpao": { emp: "Visual Propaganda", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Galpão de produção", txt: "Mais de 110 m² liberados com novo layout e fluxo de materiais.", kpi: "+110 m²" },
  "dablius-patio": { emp: "Dablius Industrial", lugar: "Conselheiro Lafaiete", prog: "bh-lafaiete-2014", titulo: "Pátio de sobras", txt: "Sucata e paletes viraram um estoque de sobras demarcado e inventariado.", kpi: "Estoque sob controle" },
  "metaltecnica-producao": { emp: "Metaltécnica", lugar: "João Monlevade", prog: "monlevade-2015", titulo: "Caldeiraria", txt: "Fluxo refeito em sequência: preparação, montagem leve, pesada, solda e acabamento.", kpi: "−60% de movimentação" },
  "qualictec-galpao": { emp: "Qualictec", lugar: "João Monlevade", prog: "monlevade-2015", titulo: "Área de recuperação", txt: "Sucata retirada, piso recuperado e espaço preparado para uma sala de treinamento.", kpi: "−40% de horas perdidas" },
  "isotec-bancada": { emp: "Isotec", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Bancada de calibração", txt: "Do canto escuro com peças soltas para uma sala limpa e padronizada.", kpi: "Posto de trabalho padronizado" },
  "metaldavi-linha": { emp: "Metaldavi", lugar: "Caxias do Sul", prog: "focem-abdi", titulo: "Linha de dobradiças", txt: "Produção empurrada virou puxada, com 5S avançado e automação de baixo custo.", kpi: "10 dias → 3,9 h" },
  "inpel-celula": { emp: "Inpel", lugar: "São Leopoldo", prog: "focem-abdi", titulo: "Célula de usinagem", txt: "Gestão à vista, fluxo e OEE na linha de transmissões mecânicas.", kpi: "−46% no custo" },
  "rcs-ferramentas": { emp: "RCS Usinagem", lugar: "Itajubá", prog: "itajuba-2019", titulo: "Gaveta de ferramentas", txt: "Cada ferramenta com lugar definido. O set-up do torno caiu de 2 horas para 30 minutos.", kpi: "−80% de set-up" },
  "jw-almox": { emp: "JW Manutenções", lugar: "João Monlevade", prog: "monlevade-2015", titulo: "Almoxarifado", txt: "Peças de talhas separadas por tipo, com paleteira e corredor livre.", kpi: "−78% de deslocamento" },
  "causimec-ferramentaria": { emp: "Causimec", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Ferramentaria", txt: "Escaninhos identificados e painel de ferramentas no ponto de uso.", kpi: "Busca por ferramenta eliminada" },
  "metaltecnica-almox": { emp: "Metaltécnica", lugar: "João Monlevade", prog: "monlevade-2015", titulo: "Almoxarifado", txt: "Prateleiras por família de item e caixas identificadas.", kpi: "460 m² liberados" },
  "tetum-obra": { emp: "Tetum Engenharia", lugar: "Patos de Minas", prog: "procompi-2017", titulo: "Canteiro de obra", txt: "5S e controle de obra no edifício-sede de uma cooperativa de crédito.", kpi: "+60% de performance" },
  "visual-corredor": { emp: "Visual Propaganda", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Corredor lateral", txt: "O corredor que guardava sobras virou passagem livre.", kpi: "Área recuperada" },
  "precisa-oficina": { emp: "Balanças Precisa", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Oficina de balanças", txt: "Empilhadeira e caixas fora do caminho, chão demarcado.", kpi: "Fluxo desobstruído" },
  "rcs-bancada": { emp: "RCS Usinagem", lugar: "Itajubá", prog: "itajuba-2019", titulo: "Centro de usinagem", txt: "Armário de ferramentas ao lado da máquina e posto limpo.", kpi: "+60% de OEE" },
};

/* Ordem curada da galeria. */
window.AG_GALLERY = ["visual-fachada", "dablius-patio", "metaltecnica-producao", "qualictec-galpao", "isotec-bancada", "metaldavi-linha", "rcs-ferramentas", "jw-almox", "visual-galpao", "causimec-ferramentaria", "tetum-obra", "inpel-celula"];

window.AG_TOOLS = [
  ["5S", "Organização", "Senso de utilização, ordem, limpeza, padronização e disciplina. A base de tudo que vem depois."],
  ["VSM", "Diagnóstico", "Mapa do fluxo de valor: do pedido à entrega, onde o tempo é gasto e onde ele é perdido."],
  ["NVAA", "Diagnóstico", "Atividade que não agrega valor. Cronoanálise separa o que o cliente paga do que é desperdício."],
  ["Spaghetti", "Diagnóstico", "Desenho dos passos reais do operador. Na Pittelli, 39 passos viraram 1."],
  ["SMED", "Fluxo", "Troca rápida de ferramenta. Na RCS, o set-up do torno CNC caiu de 2 h para 30 min."],
  ["Kaizen", "Melhoria", "Projetos curtos e focados na maior perda, conduzidos pela própria equipe da empresa."],
  ["5 Porquês", "Causa raiz", "Perguntar por que até chegar na causa que, removida, faz o problema não voltar."],
  ["4M", "Causa raiz", "Método, máquina, mão de obra e material: o diagrama de Ishikawa aplicado ao chão."],
  ["Poka-Yoke", "Qualidade", "Dispositivo à prova de erro: a peça errada não entra, o defeito não passa."],
  ["OEE", "Medição", "Disponibilidade × performance × qualidade. Uma linha de refrigeradores chegou a 77,2%."],
  ["TPM", "Manutenção", "Manutenção autônoma e profissional para a máquina parar por plano, não por quebra."],
  ["Kanban", "Fluxo", "Produção puxada pelo consumo. Na Metaldavi, um lote de 10 dias passou a sair em 3,9 h."],
  ["5W2H", "Gestão", "O quê, por quê, onde, quando, quem, como e quanto: o plano de ação que tem dono e prazo."],
  ["Muri · Mura", "Ergonomia", "Sobrecarga e irregularidade. Postos ajustados à altura do operador e carga balanceada."],
  ["SOP", "Padrão", "Procedimento operacional padrão: o melhor jeito conhecido, escrito e treinado."],
  ["B/C", "Resultado", "Benefício sobre custo. Todo projeto termina com o ganho anual medido e o payback calculado."],
];

window.AG_TIMELINE = [
  { ano: "1996", t: "FCA Fiat Chrysler · Betim", d: "Condutor do Processo Integrado. Liderança de equipe na linha de produção." },
  { ano: "1998", t: "Stola do Brasil · Belo Horizonte", d: "Quinze anos da funilaria à metodologia da qualidade. Implantação dos 20 pilares do WCM." },
  { ano: "2009", t: "Lean Automotivo", d: "Seis edições com a cadeia de fornecedores: 311 empresas e cerca de 500 projetos." },
  { ano: "2012", t: "Albert Gil Lean Consulting", d: "Funda a consultoria. Programas com SEBRAE, FIEMG, IEL, PROCOMPI e ABDI em cinco estados." },
  { ano: "2022", t: "Mikro-Stamp · Campinas", d: "Diretor industrial: produção, qualidade, logística, engenharia, manutenção e comercial." },
  { ano: "2024", t: "GW Metal · Limeira", d: "Diretor operacional à frente de dez áreas, da produção ao financeiro." },
  { ano: "2026", t: "LeanOS", d: "Software para manter vivos os ganhos de uma implantação Lean depois da consultoria." },
];

window.AG_QUOTES = [
  { q: "Agradecemos ao Albert por ter passado todo seu conhecimento e estar sempre à disposição para esclarecer as dúvidas. Agora é conosco, sempre dispostos a buscar a melhoria contínua.", who: "Erominas", ctx: "PROCOMPI Itajubá · 2019" },
  { q: "Com a Academia Lean Manufacturing mudei o meu modo de ver e de pensar.", who: "Maria Teresa Bicalho", ctx: "Gerente de produção · Rancho de Minas · 2015" },
  { q: "Fica o aprendizado de que sempre devemos buscar alcançar a situação ideal. Sempre há espaço para melhorar.", who: "Tetum Engenharia", ctx: "PROCOMPI Patos de Minas · 2017" },
];
