/* Conteúdo voltado a quem vai contratar: formatos de trabalho, casos em profundidade, perguntas
 * frequentes e o diagnóstico rápido. Números dos casos vêm das apresentações de resultados
 * (tabelas de custo de deslocamento, séries mensais e quadros de antes e depois). */

window.AG_SERVICES = [
  {
    id: "diagnostico", tag: "Primeiro passo",
    nome: "Diagnóstico de perdas",
    para: "Para quem sabe que tem dinheiro parado na operação, mas não sabe onde.",
    entrega: ["Visita ao chão de fábrica e mapa do fluxo de valor", "Cronoanálise e separação do que agrega valor", "Lista de oportunidades priorizada por ganho estimado"],
    prova: "Numa única turma em Patos de Minas, o diagnóstico levantou 229 oportunidades.",
  },
  {
    id: "implantacao", tag: "Consultoria direta",
    nome: "Implantação Lean na sua empresa",
    para: "Para a diretoria que quer resultado medido em reais, com a própria equipe conduzindo os projetos.",
    entrega: ["Projetos Kaizen nas maiores perdas, de 4 a 5 meses", "Acompanhamento de indicadores com a direção", "Benefício/custo e payback calculados por projeto"],
    prova: "Na Multibag (2024), a produção média diária subiu 18% sobre 2023.",
  },
  {
    id: "programas", tag: "Instituições",
    nome: "Programas para grupos de empresas",
    para: "Para SEBRAE, federações, sindicatos e prefeituras que querem levar o Lean a uma região ou cadeia.",
    entrega: ["Turmas de 2 a 311 empresas, cerca de 82 h por ciclo", "Capacitação em sala e projeto no posto de trabalho", "Relatório consolidado com o ganho de cada empresa"],
    prova: "Coordenou equipes de consultores em 21 programas e 6 estados, com ganho medido em cada empresa.",
  },
  {
    id: "lideres", tag: "Pessoas",
    nome: "Formação de líderes e WCM",
    para: "Para quem precisa de líderes que sustentem rotina, padrão e indicador sem depender de consultor.",
    entrega: ["Pilares do WCM, 5S com auditoria e gestão à vista", "Formação de multiplicadores dentro da empresa", "Coaching de líderes de produção"],
    prova: "Quinze anos implantando os 20 pilares do WCM na Stola do Brasil.",
  },
  {
    id: "direcao", tag: "Operações",
    nome: "Apoio à direção industrial",
    para: "Para empresas que precisam reorganizar produção, qualidade, logística e manutenção ao mesmo tempo.",
    entrega: ["Leitura integrada de produção, custos e pessoas", "Plano de ação com metas por área", "Rotina de gestão com a liderança"],
    prova: "Experiência como diretor industrial e operacional em metalúrgicas de SP.",
  },
  {
    id: "leanos", tag: "Sustentação",
    nome: "LeanOS para manter o ganho",
    para: "Para quem já melhorou e não quer ver o resultado regredir depois que o projeto acaba.",
    entrega: ["Rotinas com checklist e evidência", "Alertas de regressão com dono e prazo", "Índice de Sustentação de 0 a 100"],
    prova: "Software criado a partir do que se repetiu em centenas de programas.",
  },
];

window.AG_CASES = [
  {
    id: "metaltecnica", emp: "Metaltécnica", setor: "Caldeiraria e usinagem", lugar: "João Monlevade (MG)", ano: "2015", prog: "monlevade-2015",
    titulo: "Soldadores andavam 40 metros para buscar gás e consumível.",
    problema: "A área de solda ficava a 40 m do almoxarifado e a sucata saía por caçambas distantes. O galpão crescera sem estudo de fluxo, e o tempo de deslocamento virou custo fixo.",
    causa: "Áreas de apoio longe do ponto de uso e um layout sem sequência de processo.",
    acao: ["Solda realocada a 5 m do almoxarifado", "Caçambas de sucata dentro dos galpões e janela de descarte na máquina de corte", "Caldeiraria em sequência: preparação, montagem leve, pesada, solda e acabamento", "Duas pontes rolantes e almoxarifado junto à usinagem"],
    kpis: [["R$ 975 mil", "ganho líquido anual"], ["16,8×", "benefício/custo"], ["460 m²", "de área liberada"], ["28 t", "de sucata vendidas"]],
    chart: { tipo: "pares", titulo: "Custo anual de deslocamento por frente de trabalho", unidade: "R$", itens: [["Almoxarifado da usinagem", 109560, 43560], ["Caçambas de sucata", 40320, 16128], ["Soldagem", 22176, 8870], ["Descarte na máquina de corte", 15120, 3024], ["Sucata na usinagem", 4158, 1663]] },
    fotos: ["metaltecnica-producao", "metaltecnica-almox"],
  },
  {
    id: "rcs", emp: "RCS Usinagem", setor: "Ferramentaria e usinagem", lugar: "Itajubá (MG)", ano: "2018–2019", prog: "itajuba-2019",
    titulo: "Cada troca no torno CNC parava a máquina por três horas e meia.",
    problema: "Programar o torno levava 1,5 h e preparar a máquina, mais 2 h. No try-out, 14 peças iam para o refugo, uma perda de 28%. A máquina passava 80% do tempo parada.",
    causa: "Programação e preparação feitas com a máquina parada.",
    acao: ["SMED: tudo que pode ser feito com a máquina rodando saiu do tempo de parada", "Software próprio de programação, no conceito Indústria 4.0", "Ferramentas organizadas por posição, ao lado da máquina"],
    kpis: [["45 min", "de programação + set-up (eram 210)"], ["0", "peças de refugo no try-out"], ["+60%", "de OEE"], ["104×", "benefício/custo"]],
    chart: { tipo: "pares", titulo: "Tempo de preparação do torno CNC", unidade: "min", itens: [["Programação", 90, 15], ["Set-up", 120, 30]] },
    fotos: ["rcs-ferramentas", "rcs-bancada"],
  },
  {
    id: "ryjor", emp: "Ryjor Underwear", setor: "Confecção de moda íntima", lugar: "Nova Friburgo (RJ)", ano: "2015", prog: "friburgo-2015",
    titulo: "O corte precisava dobrar a produção sem contratar.",
    problema: "O setor de corte limitava a fábrica: 5.577 peças em março. Rebarbas geravam 21 mil peças de retrabalho por ano, ou 437 horas de duas costureiras.",
    causa: "Retrabalho de rebarba e defeito de bainha tratados no fim da linha, em vez de evitados no corte.",
    acao: ["PDCA no setor de corte com meta mensal", "OEE e 5S aplicados ao corte", "Eliminação do defeito de bainha na origem"],
    kpis: [["3,4×", "peças cortadas por mês"], ["−95%", "de retrabalho"], ["R$ 83 mil", "economizados por ano"]],
    chart: { tipo: "serie", titulo: "Peças cortadas por mês em 2015", unidade: "peças", itens: [["mar", 5577], ["abr", 8564], ["mai", 13600], ["jun", 15222], ["jul", 17135], ["ago", 19186]] },
    fotos: [],
  },
  {
    id: "carrera", emp: "Carrera", setor: "Oficina mecânica", lugar: "Belo Horizonte (MG)", ano: "2015", prog: "oficinas-2015",
    titulo: "Mecânicos perdiam o dia procurando ferramenta e peça.",
    problema: "O deslocamento interno da oficina consumia horas da equipe e segurava os carros no box. Eram 3.960 horas ociosas e improdutivas por ano.",
    causa: "Deslocamento para buscar ferramentas e peças, a perda mais comum entre as 11 oficinas da turma.",
    acao: ["Organização do posto de trabalho, eixo do programa nas 11 oficinas", "Cronoanálise e corte do deslocamento interno", "Um veículo a mais liberado por dia"],
    kpis: [["R$ 1,12 mi", "ganho líquido anual"], ["180×", "benefício/custo"], ["−96%", "de deslocamento interno"], ["+264", "veículos entregues por ano"]],
    chart: { tipo: "pares", titulo: "Deslocamento interno da oficina (antes = 100)", unidade: "", itens: [["Índice de deslocamento", 100, 4, "100", "4"]] },
    fotos: [],
  },
  {
    id: "pittelli", emp: "Pittelli Engenharia", setor: "Construção civil", lugar: "Uberlândia (MG)", ano: "2017–2018", prog: "lean-construction-2018",
    titulo: "Cada saco de cimento custava 39 passos ao servente.",
    problema: "O depósito de cimento ficava longe da betoneira. Eram 205.920 passos por ano só para abastecer a mistura, e o canteiro desorganizado travava a estrutura.",
    causa: "Material de uso contínuo guardado longe do ponto de uso.",
    acao: ["Container de cimento ao lado da betoneira", "Limpeza e organização do canteiro (5S)", "Estudo de passos e rotina de abastecimento"],
    kpis: [["39 → 1", "passo por viagem"], ["−97%", "de deslocamento"], ["+63%", "de produtividade na estrutura"]],
    chart: { tipo: "pares", titulo: "Passos por ano para abastecer a betoneira", unidade: "passos", itens: [["Abastecimento de cimento", 205920, 5280]] },
    fotos: [],
  },
  {
    id: "mrs", emp: "MRS · Cestari Freios", setor: "Autopeças", lugar: "Mauá (SP)", ano: "2013–2014", prog: "focem-abdi",
    titulo: "Vinte máquinas e vinte operadores para fazer buchas.",
    problema: "O setor de buchas tinha 20 máquinas, cada uma com um operador, bancadas espalhadas e muito deslocamento: 1.055 km e 2.455 horas por ano só andando. Quase 70% do tempo era atividade sem valor.",
    causa: "Produção organizada por hora-homem, com uma pessoa por máquina e sem fluxo entre as operações.",
    acao: ["Célula em U com 3 tornos CNC no lugar de 12 das 24 máquinas", "Produção por hora-máquina, com 1 operador na célula", "Linhas obsoletas vendidas e espaço cedido a um novo cliente", "5S e manutenção preventiva"],
    kpis: [["20 → 3", "máquinas na célula"], ["20 → 1", "operadores"], ["68,7% → 22,4%", "tempo sem valor"], ["R$ 430 mil", "ganho anual projetado"]],
    chart: { tipo: "pares", titulo: "Setor de buchas, antes e depois", unidade: "", itens: [["Máquinas", 20, 3, "20", "3"], ["Operadores", 20, 1, "20", "1"], ["Tempo sem valor (%)", 68.68, 22.43, "68,7%", "22,4%"]] },
    fotos: [],
  },
  {
    id: "metaldavi", emp: "Metaldavi", setor: "Metalmecânica", lugar: "Caxias do Sul (RS)", ano: "2013–2014", prog: "focem-abdi",
    titulo: "Um pedido de 600 dobradiças levava dez dias.",
    problema: "A produção era empurrada em lotes grandes, com estoque entre etapas e fábrica desorganizada.",
    causa: "Produção empurrada em lotes grandes.",
    acao: ["5S intermediário e avançado", "Automação de baixo custo nas operações críticas", "Produção puxada pelo pedido"],
    kpis: [["3,9 h", "para o mesmo lote (eram 10 dias)"], ["−95,8%", "de lead time"], ["43% → 83%", "OEE"]],
    chart: { tipo: "pares", titulo: "Tempo para produzir 600 dobradiças", unidade: "h", itens: [["Lote de 600 dobradiças", 240, 3.9, "10 dias", "3,9 h"]] },
    fotos: ["metaldavi-linha"],
  },
  {
    id: "graal", emp: "Restaurante Graal Embaixador", setor: "Restaurante de estrada", lugar: "Volta Redonda (RJ)", ano: "2016", prog: "volta-redonda",
    titulo: "Cada funcionário perdia 70 minutos antes de começar a cozinhar.",
    problema: "Receitas sem padrão, produção no improviso e a comida chegando à estufa entre 12h e 12h30. O cozinheiro andava até 2.381 passos por dia, e as sobras somavam R$ 58,8 mil em 28 dias.",
    causa: "Gestão no feeling: sem receita padrão, sem estoque mínimo na despensa e sem regra de primeiro que entra, primeiro que sai.",
    acao: ["Cardápio semanal fixo e receitas padronizadas", "Estoque mínimo e PEPS na despensa", "Carrinhos, caixas identificadas e quadro de comunicação entre turnos", "Cozinha sem trânsito de quem não cozinha"],
    kpis: [["70 → 0 min", "de start-up por funcionário"], ["−81%", "de deslocamento"], ["R$ 51 mil", "de ganho por mês"], ["11h", "comida pronta na estufa"]],
    chart: { tipo: "pares", titulo: "Cozinha do restaurante, por mês", unidade: "", itens: [["Start-up por funcionário", 70, 0, "70 min", "0 min"], ["Passos por dia (cozinha)", 145, 28, "145", "28"], ["Sobras de comida", 893, 777, "893 kg", "777 kg"], ["Compras da cozinha", 259147, 242483, "R$ 259 mil", "R$ 242 mil"]] },
    fotos: [],
  },
  {
    id: "tirolez", emp: "Tirolez · Unidade de Tiros", setor: "Laticínios", lugar: "Tiros (MG)", ano: "2017", prog: "procompi-2017",
    titulo: "2,8% de cada lote de queijo virava perda no fracionamento.",
    problema: "Cerca de 25 kg de queijo coalho perdidos por lote no corte e na embalagem, além de 4.180 passos de deslocamento por turno.",
    causa: "Gabarito com facas em excesso, sistema de fracionamento ultrapassado e prensagem sem tempo padrão.",
    acao: ["Uma viragem do queijo eliminada e maior compactação", "Padrão de prensagem com tempo definido", "Caixa coletora de finos", "Sal de 200 para 150 kg por lote"],
    kpis: [["−31,7%", "de perda de massa"], ["−62,5%", "de homem-hora na embalagem"], ["−25%", "de sal por lote"], ["11×", "benefício/custo"]],
    chart: { tipo: "pares", titulo: "Por lote de queijo coalho", unidade: "", itens: [["Perda de massa", 23.19, 15.83, "23,2 kg", "15,8 kg"], ["Homem-hora na embalagem", 3.33, 1.25, "3,33", "1,25"], ["Sal", 200, 150, "200 kg", "150 kg"]] },
    fotos: [],
  },
];

window.AG_FAQ = [
  ["Preciso parar a produção para implantar?", "Não. Os projetos acontecem na rotina, com a equipe da empresa. A parte em sala soma cerca de 28 horas no ciclo; o resto é feito no posto de trabalho."],
  ["Em quanto tempo aparece resultado?", "Os programas consolidam o resultado em 4 a 5 meses. Em Patos de Minas, 10 de 11 empresas recuperaram o investimento em menos de um mês."],
  ["Funciona para empresa pequena?", "Sim. A maior parte das empresas desta página são pequenas e médias: oficinas, confecções, padarias, restaurantes, construtoras e metalúrgicas."],
  ["Funciona fora da indústria?", "Sim. Há resultados em reparação automotiva, construção civil, alimentos, restaurantes, lavanderia, comércio, serviços e gestão pública."],
  ["Como o resultado é medido?", "Cada projeto fecha com o ganho anual calculado pela empresa, o custo do projeto, o benefício/custo e o payback. Tudo vai para um relatório final."],
  ["E se a equipe voltar ao jeito antigo?", "O método termina em padrão e indicador. Para quem quer acompanhamento diário, o LeanOS mede a rotina e avisa quando o resultado começa a regredir."],
  ["Vocês atendem fora de Minas Gerais?", "Sim. Já houve turmas em Minas, Rio de Janeiro, São Paulo, Espírito Santo, Rio Grande do Sul e Pernambuco."],
  ["Quanto custa?", "Depende do formato e do tamanho da operação. Programas em grupo podem ter parte do custo coberta pela instituição parceira. O que se mede sempre é o retorno: o benefício/custo mediano das empresas desta página é de 31 vezes."],
];

window.AG_QUIZ = [
  { id: "setor", q: "Qual é a sua operação?", opts: [["ind", "Indústria"], ["ofi", "Oficina ou serviço automotivo"], ["con", "Construção civil"], ["ali", "Alimentos"], ["ser", "Comércio ou serviços"], ["inst", "Instituição que atende várias empresas"]] },
  { id: "dor", q: "O que mais incomoda hoje?", opts: [["prod", "Produtividade baixa e prazo atrasado"], ["custo", "Custo alto e desperdício"], ["org", "Desorganização, procura e falta de espaço"], ["pessoas", "Equipe sem método e liderança fraca"], ["regride", "Melhorias que não se sustentam"]] },
  { id: "porte", q: "Quantas pessoas trabalham na operação?", opts: [["p", "Até 20"], ["m", "De 20 a 100"], ["g", "Mais de 100"]] },
];
