/* Base curada do portfólio Albert Gil.
 * Fontes: apresentações de resultados, análises de benefício/custo e planilhas consolidadas dos programas.
 * Valores em R$ são ganhos líquidos anuais declarados pelas empresas ao fim de cada programa.
 * `p:true` marca valor projetado e `x:true` valor sem confirmação documental: os dois ficam fora das somas
 * e o valor não é exibido. `semTotal` indica programa sem o ganho de todas as empresas.
 */
window.AG_SECTORS = {
  ind: "Indústria",
  ofi: "Reparação automotiva",
  ali: "Alimentos",
  con: "Construção civil",
  ser: "Comércio e serviços",
  pub: "Gestão pública",
};

window.AG_PROGRAMS = [
  {
    id: "lean-automotivo", semTotal: true,
    nome: "Academia Lean · Fornecedores Fiat",
    ano: 2010, anoLabel: "2010–2012",
    parceiro: "Fiat · Universidade de Fornecedores · ICE",
    local: "Minas Gerais e São Paulo",
    cidades: ["Betim", "Belo Horizonte"],
    setores: ["ind"],
    e: 27,
    resumo: "Programa de desenvolvimento de fornecedores da Fiat. Albert foi padrinho de grupo em 2010 (Stola, Takata, Minas Plastic e Dayco) e instrutor de produtividade na 4ª edição, com cerca de 14 empresas em MG e 13 em SP.",
    kpis: [["+82%", "produtividade (Olsa)"], ["9 → 6", "pessoas na linha Tritec (Sumidenso)"], ["−40%", "estoque em processo (ZF)"]],
    empresas: [
      { n: "Olsa do Brasil", s: "Autopeças · SP", r: "Luz de placa do Strada de 155 para 189 peças/h, com 3 para 2 operadores" },
      { n: "Sumidenso do Brasil", s: "Autopeças · MG", r: "Linha Tritec com 6 pessoas no lugar de 9 e 16% menos área" },
      { n: "ZF Sistemas de Direção", s: "Autopeças · MG", r: "−40% de estoque em processo na coluna de direção" },
      { n: "Stola do Brasil", s: "Carrocerias · BH", r: "Puntone do Novo Uno: NVAA de 58,9% para 34,4%, B/C 3,18" },
    ],
    fotos: [],
  },
  {
    id: "focem-abdi", semTotal: true,
    nome: "FOCEM Auto · ABDI",
    ano: 2013, anoLabel: "2013–2014",
    parceiro: "ABDI · FOCEM Mercosul · ICE",
    local: "ABC paulista e Mauá (SP)",
    cidades: ["Santo André", "Mauá", "São Bernardo do Campo", "Diadema"],
    setores: ["ind"],
    e: 10,
    resumo: "Projeto federal de adensamento da cadeia de autopeças do Mercosul (contrato ABDI 11/2013). Albert foi o consultor de 10 pequenas e médias empresas paulistas, de outubro de 2013 a setembro de 2014, e assina os relatórios finais. As empresas projetaram cerca de R$ 1,06 mi de ganho anual.",
    kpis: [["20 → 3", "máquinas na célula de buchas (MRS)"], ["17% → 89%", "OEE (Alumec)"], ["5S 7% → 95%", "auditoria (Jodeclan)"]],
    empresas: [
      { n: "MRS · Cestari Freios", s: "Autopeças · Mauá", g: 430000, p: true, r: "Setor de buchas de 20 máquinas e 20 operadores para célula com 3 máquinas e 1 operador; NVAA de 68,7% para 22,4%" },
      { n: "Alumec", s: "Usinagem · Diadema", g: 170000, p: true, r: "Set-up de 45 para 22 min, OEE de 17% para 89%, novo cliente: Iveco" },
      { n: "Ferosão J.C.R.", s: "Usinagem · São Bernardo do Campo", g: 129000, p: true, r: "OEE de 75% para 97%, +41% de disponibilidade de máquina" },
      { n: "Modelarte", s: "Modelos e moldes · Mauá", g: 100000, p: true, r: "Área de solda de 136 para 27 passos/dia (−80%)" },
      { n: "Overdrill Máquinas", s: "Diadema", g: 59000, p: true, r: "Set-up de 38 para 22 min, NVAA de 72% para 31%" },
      { n: "Ecoplas ABC", s: "Plásticos · São Caetano do Sul", g: 52000, p: true, r: "5S de 27% para 95%, kanban liberou metade do espaço" },
      { n: "Jodeclan Ferramentaria", s: "São Bernardo do Campo", g: 47000, p: true, r: "Set-up de 65 para 28 min, NVAA de 91% para 21,6%" },
      { n: "Keefer Máquinas e Moldes", s: "São Bernardo do Campo", g: 37000, p: true, r: "Set-up de 42 para 18 min" },
      { n: "Eliu · Grupo Taurus", s: "Ferramentaria · Diadema", g: 37000, p: true, r: "NVAA de 86% para 17%, 5S de 17% para 95%" },
      { n: "Kruth do Brasil", s: "São Bernardo do Campo", r: "Projeto 5S sem evolução: empresa operando a 15% da capacidade" },
    ],
    fotos: [],
  },
  {
    id: "bh-lafaiete-2014",
    nome: "Academia Lean · BH e Conselheiro Lafaiete",
    ano: 2014, anoLabel: "2014",
    parceiro: "SEBRAE Minas · Sebraetec",
    local: "Grande BH e Conselheiro Lafaiete (MG)",
    cidades: ["Belo Horizonte", "Conselheiro Lafaiete"],
    setores: ["ind", "ser"],
    e: 19,
    resumo: "De junho a novembro de 2014, mais de 680 horas de treinamento e consultoria em 12 empresas da Grande BH e 7 de Conselheiro Lafaiete. Albert e Fábio Mota foram os instrutores da turma de BH.",
    kpis: [["3,5×", "produção por hora (Soma)"], ["−95%", "NVAA no centro de usinagem (Delta)"], ["−75%", "material de higienização (Locsan)"]],
    empresas: [
      { n: "Soma Usinagem e Caldeiraria", s: "Usinagem · Lafaiete", g: 252912, bc: 53.04, r: "Anel de encosto de 8 h para 4 h, produção por hora 3,5×, custo −57%" },
      { n: "Locsan", s: "Serviços · Lafaiete", g: 185500, bc: 54, r: "−75% de material de higienização, controle de uniformes e EPI" },
      { n: "HB Locações", s: "Locação · Lafaiete", g: 165372, bc: 5.66, r: "−50% de material por semana na rota da cidade" },
      { n: "CompIT", s: "Assistência técnica em TI · BH", g: 118415, bc: 7.08, r: "De 1,6 para 4,05 equipamentos por técnico/dia (+153%)" },
      { n: "Suporte Automação Industrial", s: "Automação · Matozinhos", g: 115786, bc: 12.03, r: "Galpão reorganizado; 3.743 passos por ciclo eliminados em boa parte" },
      { n: "Dedetizar", s: "Serviços · BH", g: 97196, bc: 22.6, r: "Horas extras de domingo cortadas pela metade" },
      { n: "Isotec", s: "Instrumentos de medição · BH", g: 95277, bc: 29.02, r: "−50% de atraso na entrega, −30% de deslocamento" },
      { n: "Premoldados Matozinhos", s: "Construção", g: 71421, bc: 48.61, r: "−33% de deslocamento, 2 pessoas realocadas" },
      { n: "Lavanderia Santo Antônio", s: "Serviços · BH", g: 58580, bc: 12.7, r: "Calandra de 5 para 3 pessoas, retrabalho em queda" },
      { n: "Causimec", s: "Usinagem", g: 36828, bc: 2.64, r: "Torneiros de 46 para 5 passos por ciclo" },
      { n: "Balanças Precisa", s: "Metrologia", g: 35658, bc: 8.73, r: "−75% de deslocamento na área técnica" },
      { n: "Silk Artes", s: "Comunicação visual · Lafaiete", g: 22464, bc: 15.4, r: "Retrabalho no design de 4 h para 1 h por dia" },
      { n: "Dablius Industrial", s: "Caldeiraria · Lafaiete", g: 19009, bc: 10.54, r: "Sobras de chapa inventariadas e rastreáveis (ISO 9001)" },
      { n: "Delta Industrial", s: "Usinagem · BH", bc: 28.99, r: "−95% de NVAA no centro de usinagem" },
      { n: "Gráfica Caraça", s: "Gráfica", bc: 8.93, r: "+89% de performance nos três primeiros sensos do 5S" },
      { n: "Fran Motores", s: "Rebobinagem", bc: 10.39, r: "Desperdício de fio na rebobinagem com regra por número de polos" },
      { n: "Visual Propaganda", s: "Comunicação visual · Barão de Cocais", r: "−69% de deslocamento e mais de 110 m² liberados" },
    ],
    fotos: ["delta-usinagem", "lavanderia-galpao", "suporte-bancada", "visual-fachada", "visual-galpao", "delta-fresa", "suporte-fixadores", "dablius-patio", "isotec-bancada", "precisa-oficina", "causimec-ferramentaria", "compit-bancada", "visual-corredor", "visual-recepcao", "visual-patio"],
  },
  {
    id: "fiat-industrial-2013", semTotal: true,
    nome: "Academia Lean Industrial · Fiat e CNH",
    ano: 2013, anoLabel: "2013–2014",
    parceiro: "Grupo Fiat · Academia Lean",
    local: "Fornecedores em MG e SP",
    cidades: [],
    setores: ["ind"],
    e: 8,
    resumo: "Turma para fornecedores do Grupo Fiat e da CNH, com Albert e Fábio Mota como instrutores. Cada empresa levou um projeto de produtividade ou qualidade da sala para a linha.",
    kpis: [["24 → 16", "operadores (Brose)"], ["27,5 h → 3,5 h", "lead time por peça (Inbrasc)"], ["+100%", "itens soldados (Imperador)"]],
    empresas: [
      { n: "Brose do Brasil", s: "Autopeças", r: "Rebitagem +33%, de 24 para 16 operadores e fim do terceiro turno" },
      { n: "Allevard Molas · Grupo Sogefi", s: "Autopeças", r: "Montagem de buchas de 48 para 72 peças/h (+50%), refugo zerado" },
      { n: "Inbrasc", s: "Componentes · cliente CNH", g: 32723, r: "Lead time de 27,5 h para 3,5 h, 30 m² liberados" },
      { n: "Travi Plásticos", s: "Plásticos", r: "Operação de 250 para 180 s (−28%)" },
      { n: "Imperador Mecânica", s: "Mecânica industrial", r: "Itens soldados de 25 para 50 por dia" },
      { n: "Tuzzi", s: "Usinagem e solda", r: "−58% no tempo de usinagem do sensor, retrabalho eliminado" },
      { n: "Zukauskas", s: "Usinagem", r: "Três operações reunidas em uma, dispositivo para duas peças" },
    ],
    fotos: [],
  },
  {
    id: "fiat-2tier-2014",
    nome: "Academia Lean 2 Tier · SEBRAE e Fiat",
    ano: 2014, anoLabel: "2014–2015",
    parceiro: "SEBRAE Minas · Fiat",
    local: "Belo Horizonte e Sete Lagoas (MG)",
    cidades: ["Belo Horizonte", "Sete Lagoas"],
    setores: ["ind", "ali"],
    e: 6,
    resumo: "Fornecedores de segundo nível da cadeia Fiat, de outubro de 2014 a março de 2015. Destaque para uma fábrica de massas que praticamente eliminou o refugo da lasanha.",
    kpis: [["108×", "benefício/custo (Massas Terni)"], ["−90%", "tempo de set-up (Padrão Minas)"], ["157 → 15", "passos por trajeto (Embalex)"]],
    empresas: [
      { n: "Massas Terni", s: "Alimentos", g: 245768, bc: 108.2, r: "Refugo da massa de lasanha −86,6%, retrabalho −88%, 2.376 h de produção liberadas" },
      { n: "Padrão Minas", s: "Comunicação visual", g: 88397, bc: 21.32, r: "Set-up médio −90%, −30% de vinil, 1 pessoa realocada" },
      { n: "Embalex", s: "Embalagens", g: 50219, bc: 28.28, r: "De 157 para 15 passos por trajeto, 3.140 h para 30 h por ano" },
      { n: "Félix Quality Print", s: "Pintura eletrostática · Sete Lagoas", g: 190872, bc: 18.22, x: true, r: "NVAA −76% (300 para 120 passos), 5S em 95%" },
      { n: "Usifor" },
      { n: "Setor Elétrico" },
    ],
    fotos: [],
  },
  {
    id: "oficinas-2015",
    nome: "Lean na Reparação Automotiva",
    ano: 2015, anoLabel: "2015",
    parceiro: "SEBRAE Minas · SINDIREPA-MG · ICE",
    local: "Belo Horizonte e Contagem (MG)",
    cidades: ["Belo Horizonte"],
    setores: ["ofi"],
    e: 15,
    resumo: "Albert diagnosticou 20 oficinas entre março e abril de 2015. Quinze seguiram para o programa em duas turmas, com organização do posto de trabalho, cronoanálise e balanceamento para liberar mais carros por dia com a mesma equipe.",
    kpis: [["−96%", "deslocamento interno (melhor caso)"], ["+50%", "veículos entregues (melhor caso)"], ["3.960 h", "ociosas eliminadas por ano"]],
    empresas: [
      { n: "Carrera", g: 1118282, bc: 179.64, r: "−96% de NVAA de deslocamento, +17% de produtividade (264 veículos/ano), 3.960 h ociosas a menos" },
      { n: "Centro Automotivo Santa Efigênia", g: 928605, bc: 21.32, r: "−94% de NVAA, +50% de produtividade (1.056 veículos/ano)" },
      { n: "Rodricar", g: 695897, bc: 36.15, r: "−70% de NVAA, +20% de produtividade" },
      { n: "Autorom", g: 681911, bc: 420, r: "+25% de produtividade (180 veículos/ano), 1.440 h ociosas a menos" },
      { n: "Prima Línea", g: 676847, bc: 25.56, r: "−97% de NVAA, +17% de produtividade" },
      { n: "Safira", g: 508940, bc: 13.41, r: "+18% de produtividade, −40% de insumos" },
      { n: "Mecânica Gilmar", g: 461960, bc: 48.98, r: "−96% de NVAA, 3 profissionais realocados" },
      { n: "Motorplan", g: 171678, bc: 9.75, r: "−95% de NVAA, 2.640 h ociosas a menos" },
      { n: "Kadosh", g: 112707, bc: 70.2, r: "3 profissionais realocados" },
      { n: "Mecalazo", g: 111153, bc: 67.8, r: "De 80 para 10 passos por serviço, NVAA de 85% para 15%" },
      { n: "Moraes", g: 109428, bc: 68.2, r: "+10% de produtividade, horas extras zeradas" },
      { n: "Check Car", g: 85108, bc: 53.28, r: "21% da mão de obra otimizada, kanban de fluxo de veículos" },
      { n: "Cafcar", g: 71424, bc: 44.87, r: "+12% de produtividade com um profissional a menos" },
      { n: "Pachauto", g: 10372, bc: 7.37, r: "130 m² de espaço ocioso recuperado, aluguel −12%" },
      { n: "Montanha", g: 189222, bc: 72.19, x: true, r: "−27% de deslocamento, −20% de estoque" },
    ],
    fotos: [],
  },
  {
    id: "friburgo-2015", semTotal: true,
    nome: "Academia Lean · Nova Friburgo",
    ano: 2015, anoLabel: "2015",
    parceiro: "SEBRAE Rio",
    local: "Nova Friburgo (RJ)",
    cidades: ["Nova Friburgo"],
    setores: ["ind", "ali", "ser"],
    e: 14,
    resumo: "Catorze empresas de oito setores, do polo de moda íntima a fechaduras, injeção plástica e farmácia de manipulação. Cerca de 73 pessoas capacitadas.",
    kpis: [["3,4×", "produção do corte (Ryjor)"], ["−85,4%", "set-up de injetoras"], ["−96%", "falhas de equipamento (Haga)"]],
    empresas: [
      { n: "Ryjor Underwear", s: "Moda íntima", g: 83200, r: "Corte de 5.577 para 19.186 peças/mês, −95% de retrabalho" },
      { n: "Haga Fechaduras", s: "Fechaduras e ferragens", r: "Falhas de equipamento de 110 para 4 ocorrências" },
      { n: "Hela Fechaduras", s: "Fechaduras e ferragens", r: "Até +98% de produtividade na linha de vidro" },
      { n: "Sistal", s: "Segurança eletrônica", r: "+30% de produtividade na manutenção (meta era 10%)" },
      { n: "Fórmula Exata", s: "Farmácia de manipulação", r: "+25% de produtividade, +11,5% de faturamento" },
      { n: "Massa da Serra", s: "Alimentos", r: "+13% no cozimento, +24% de área de atendimento" },
      { n: "Lucitex Lingerie", s: "Moda íntima", r: "Padronização da confecção e redução de NVAA" },
    ],
    fotos: [],
  },
  {
    id: "monlevade-2015",
    nome: "Programa Lean · João Monlevade",
    ano: 2015, anoLabel: "2015",
    parceiro: "SEBRAE · Regional Rio Doce · ICE",
    local: "João Monlevade (MG)",
    cidades: ["João Monlevade"],
    setores: ["ind", "ali", "ser"],
    e: 13,
    resumo: "Treze empresas do Vale do Aço, de caldeirarias que atendem a siderurgia a uma fábrica de pão de queijo. Quatro meses de projeto, de agosto a novembro, com 36 horas de capacitação.",
    kpis: [["460 m²", "liberados na Metaltécnica"], ["−87%", "espera por ponte rolante"], ["86%", "nota 5S na JW (meta 80%)"]],
    empresas: [
      { n: "Metaltécnica", s: "Caldeiraria e usinagem", g: 975238, bc: 16.77, r: "Solda de 40 m para 5 m do almoxarifado, −60% a −80% de movimentação, 460 m² liberados" },
      { n: "Qualictec", s: "Mecânica industrial", g: 732242, bc: 5.19, r: "Horas perdidas em deslocamento de 611 para 244 por ano (−40%)" },
      { n: "Dacalp", s: "Indústria", g: 433792, bc: 64.05, r: "+25% de produtividade, 3.660 h ociosas a menos por ano" },
      { n: "JW Manutenções", s: "Manutenção de talhas", g: 97582, bc: 25.72, r: "−78% de deslocamento, 88 m² liberados, arquivos 100% padronizados" },
      { n: "Jatear", s: "Tratamento anticorrosivo", g: 82152, bc: 40.12, r: "NVAA zerado na pintura, performance dobrada" },
      { n: "Festas Práticas", s: "Locação para eventos", g: 52896, bc: 2.04, r: "+59% de performance na loja, −20% de avarias" },
      { n: "Ludor", s: "Soluções tecnológicas", g: 40923, bc: 12.18, r: "−67% de NVAA, −25% de atraso em ordens de serviço" },
      { n: "Autotécnica", s: "Oficina", g: 33600, bc: 16, r: "−58% de NVAA com 5S" },
      { n: "Rancho de Minas", s: "Pão de queijo e biscoitos", g: 3403626, bc: 40.98, p: true, r: "−79% de retrabalho no corte, capacidade de congelamento triplicada" },
      { n: "Metalúrgica Solução", s: "Metalurgia", r: "−87% de NVAA, +85% de produtividade" },
      { n: "Metainox", s: "Metalurgia", r: "−80% de NVAA com novo layout" },
      { n: "Enjatec", s: "Caldeiraria e usinagem", r: "−95% de NVAA na solda; voltou em 2016 para processos gerenciais" },
    ],
    fotos: ["metaltecnica-almox", "metaltecnica-producao", "jw-almox", "qualictec-galpao", "qualictec-ponte"],
  },
  {
    id: "ipatinga-2015", semTotal: true,
    nome: "Academia Lean · Vale do Aço",
    ano: 2015, anoLabel: "2015",
    parceiro: "IEL · AICE",
    local: "Ipatinga, Timóteo e Santana do Paraíso (MG)",
    cidades: ["Ipatinga"],
    setores: ["ind", "ser"],
    e: 8,
    resumo: "Programa de 84 horas para oito empresas do Vale do Aço, de agosto a novembro de 2015: palestra de abertura, três sessões coletivas e visitas de monitoramento em cada empresa.",
    kpis: [["84 h", "de programa por turma"], ["8", "empresas atendidas"], ["4–5 meses", "até o fechamento"]],
    empresas: [{ n: "Ramac" }, { n: "Thermon" }, { n: "Art Visão" }, { n: "Emfer" }, { n: "Meic" }, { n: "Germil" }, { n: "Líder" }, { n: "Viga" }],
    fotos: [],
  },
  {
    id: "sebraetec-2015",
    nome: "Consultorias Sebraetec",
    ano: 2015, anoLabel: "2015",
    parceiro: "SEBRAE Minas · Sebraetec",
    local: "Minas Gerais",
    cidades: [],
    setores: ["ali", "ser"],
    e: 2,
    resumo: "Projetos individuais pelo Sebraetec, com diagnóstico, projeto de melhoria e análise de benefício/custo.",
    kpis: [["43×", "benefício/custo (Meridional)"], ["+50%", "produtividade de salgados"], ["−20%", "insumos"]],
    empresas: [
      { n: "Meridional Lanches", s: "Salgados e pão de queijo", g: 354328, bc: 43.04, r: "+50% de produtividade, dois produtos novos, −20% de insumos, 5S de 7% para 86%" },
      { n: "Planeta Festas", s: "Locação para festas · Nova Lima", g: 140334, bc: 5.27, p: true, r: "Mudança de galpão e organização; ganho inclui previsão de faturamento" },
    ],
    fotos: [],
  },
  {
    id: "petropolis",
    nome: "Programa Lean · Petrópolis e Teresópolis",
    ano: 2015, anoLabel: "2015–2016",
    parceiro: "SEBRAE Rio · ICE",
    local: "Petrópolis, Teresópolis e Magé (RJ)",
    cidades: ["Petrópolis"],
    setores: ["ind", "ali", "ser"],
    e: 9,
    resumo: "Nove empresas da serra fluminense, a maioria do polo de moda. Abertura em 24 de agosto de 2015, três sessões coletivas e visitas em cada fábrica até o fechamento, em março de 2016.",
    kpis: [["32% → 1,6%", "retrabalho (Thiamo)"], ["58%", "do tecido internalizado (Vizoo)"], ["+25%", "produção mensal (Pássaro Livre)"]],
    empresas: [
      { n: "MM Plastic", s: "Injeção plástica", g: 2376677, bc: 191, r: "−50% de NVAA, 5 pessoas realocadas" },
      { n: "Graças Torradas", s: "Alimentos", g: 957103, bc: 214, r: "−83% de absenteísmo, −58% de estoque" },
      { n: "Vizoo", s: "Moda jeans", g: 710719, bc: 33.5, r: "58% do tecido internalizado, +30% de produção, −45% de deslocamento, 117 m² liberados" },
      { n: "Sinal Publicidade", s: "Comunicação visual · Magé", g: 398257, bc: 41.7, r: "−72% de NVAA, +25% de produtividade" },
      { n: "Incisor", s: "Metalurgia · Teresópolis", g: 270954, bc: 12.6, r: "−95% de NVAA, +57% de produtividade" },
      { n: "Thiamo", s: "Malhas e confecção", g: 255794, bc: 19.17, r: "Retrabalho de 32% para 1,6%: custo de R$ 172 mil para R$ 8,6 mil por ano" },
      { n: "Kappauns", s: "Serviço técnico", g: 194354, bc: 9.85, r: "Produtividade dobrada, −67% de retrabalho" },
      { n: "Pássaro Livre", s: "Malhas", g: 3448651, bc: 154, x: true, r: "Estoque −40%, horas extras zeradas, produção de 23.240 para 29.050 peças/mês" },
      { n: "Oficina 16", s: "Confecção", g: 2317403, bc: 222, x: true, r: "Estoque de matéria-prima −60% e custos gerais −22%" },
    ],
    fotos: [],
  },
  {
    id: "volta-redonda",
    nome: "Programa Lean · Volta Redonda",
    ano: 2016, anoLabel: "2016–2017",
    parceiro: "SEBRAE Rio",
    local: "Volta Redonda e Médio Paraíba (RJ)",
    cidades: ["Volta Redonda"],
    setores: ["ind", "ali", "ser", "con"],
    e: 10,
    resumo: "Dez empresas do Médio Paraíba, de olaria e laticínio a hortifrúti, guindastes e um restaurante de estrada que deixou de perder 70 minutos por funcionário no início do turno.",
    kpis: [["70 → 0 min", "de start-up na cozinha (Graal)"], ["−81%", "deslocamento (Graal)"], ["−80%", "estoque (Olaria)"]],
    empresas: [
      { n: "Resen Munck", s: "Guindastes", g: 1028923, r: "−29% de horas extras, +36% de faturamento" },
      { n: "VR Horti Fruti", s: "Alimentos", g: 753963, r: "−70% de deslocamento, −60% de custos diretos" },
      { n: "Restaurante Graal Embaixador", s: "Restaurante de estrada", g: 617472, r: "Start-up de 70 min zerado, −81% de NVAA, −13% de sobras, −6,4% em compras" },
      { n: "Inspire-se", g: 565682, r: "+91% de crescimento do negócio" },
      { n: "Olaria São Sebastião", g: 522000, r: "−80% de estoque, +10% de produtividade" },
      { n: "KVG Engenharia", s: "Engenharia", g: 240000, r: "−35% de horas ociosas, −20% de custos diretos" },
      { n: "Vó Alzira", s: "Alimentos", g: 108551, r: "−30% de deslocamento, 35% da mão de obra otimizada" },
      { n: "Laticínios Clarice", s: "Alimentos", g: 66422, r: "+30% de performance, −10% de custos diretos" },
      { n: "Dental Karisma", g: 101529, x: true, r: "30% da mão de obra otimizada" },
      { n: "Rede Construir" },
    ],
    fotos: [],
  },
  {
    id: "rio-2017",
    nome: "Programa Lean · Rio e Baixada Fluminense",
    ano: 2017, anoLabel: "2017",
    parceiro: "SEBRAE Rio",
    local: "Rio de Janeiro e Baixada Fluminense (RJ)",
    cidades: ["Rio de Janeiro", "Duque de Caxias"],
    setores: ["ind", "ser"],
    e: 6,
    resumo: "Seis empresas entre indústria, logística, locação e varejo. Onze postos de trabalho realocados para atividades que agregam valor.",
    kpis: [["R$ 4,5 mi", "ganho líquido anual"], ["−95%", "deslocamento (Espirodutos)"], ["400 m²", "liberados (JA Logística)"]],
    empresas: [
      { n: "Nova Peças", g: 2099616, r: "+10% de ticket médio, 2 pessoas realocadas" },
      { n: "Espirodutos", g: 1020000, r: "−95% de deslocamento, 8 pessoas realocadas" },
      { n: "Alfatec", s: "Refrigeração industrial", g: 809000, r: "−61% de deslocamento, OEE de 77,2% na montagem" },
      { n: "Violeta Skate Rock", g: 398000, r: "−25% de estoque, −50% de custos diretos" },
      { n: "PTA Rental", g: 120000, r: "Performance da função 2,2× maior" },
      { n: "JA Logística", g: 49200, r: "400 m² liberados e estoque sob controle" },
    ],
    fotos: [],
  },
  {
    id: "sete-lagoas-2017",
    nome: "Programa Lean · Sete Lagoas",
    ano: 2017, anoLabel: "2017",
    parceiro: "SEBRAE Minas",
    local: "Sete Lagoas (MG)",
    cidades: ["Sete Lagoas"],
    setores: ["ind", "ser"],
    e: 6,
    resumo: "Seis empresas da região central de Minas, com destaque para uma fabricante de equipamentos que cortou 80% dos custos diretos do processo.",
    kpis: [["R$ 2,4 mi", "ganho líquido anual"], ["−80%", "custos diretos (Hystermaq)"], ["+71%", "crescimento (Prática)"]],
    empresas: [
      { n: "Hystermaq", g: 1347850, r: "−80% de custos diretos, +34% de produtividade" },
      { n: "Prática Consultoria", g: 410000, r: "+71% de crescimento do negócio" },
      { n: "Lubrifrança", g: 206000, r: "−84% de deslocamento e de NVAA em set-up" },
      { n: "Teyte Modas", g: 180000, r: "−37,5% de estoque" },
      { n: "Central da Economia", g: 135000, r: "Performance da função dobrada, estoque sob controle" },
      { n: "Traço Comunicação", g: 78000, r: "26% da mão de obra otimizada" },
    ],
    fotos: [],
  },
  {
    id: "procompi-2017",
    nome: "PROCOMPI · Alto Paranaíba e Triângulo",
    ano: 2017, anoLabel: "2017",
    parceiro: "PROCOMPI · FIEMG · SEBRAE",
    local: "Patos de Minas e Triângulo Mineiro (MG)",
    cidades: ["Patos de Minas"],
    setores: ["ind", "ali", "con"],
    e: 5,
    resumo: "Cinco empresas e 229 oportunidades de melhoria mapeadas, de uma fábrica de bolsas a um laticínio de queijo coalho e uma obra de edifício-sede.",
    kpis: [["831×", "benefício/custo (Julev)"], ["−31,7%", "perda de queijo (Tirolez)"], ["229", "oportunidades mapeadas"]],
    empresas: [
      { n: "Julev Bolsas", g: 1570000, bc: 831, r: "+100% de produtividade em bolsas, +42% em carteiras, −90% de NVAA" },
      { n: "Levfort", g: 1200000, bc: 808, r: "−73% de NVAA, +15% de produtividade" },
      { n: "Bota Brasil", g: 561000, bc: 40.5, r: "−50% de horas ociosas, −50% de horas extras da liderança" },
      { n: "Tirolez · Tiros", s: "Laticínios", g: 82698, bc: 11.2, r: "−31,7% de perda de massa, −62,5% de homem-hora na embalagem" },
      { n: "Tetum Engenharia", s: "Construção · obra Sicoob Credicopa", r: "+60% de performance com 5S e controles de obra" },
    ],
    fotos: ["tetum-obra"],
  },
  {
    id: "iel-triangulo-2017",
    nome: "IEL PCIR · Araxá, Patos e Uberlândia",
    ano: 2017, anoLabel: "2017",
    parceiro: "IEL · FIEMG",
    local: "Araxá, Patos de Minas e Uberlândia (MG)",
    cidades: ["Araxá", "Patos de Minas", "Uberlândia"],
    setores: ["ind", "ali", "ser"],
    e: 13,
    resumo: "Programa de competitividade industrial regional do IEL com indústrias de fertilizantes, alimentos, destilarias e serviços.",
    kpis: [["−99%", "refugo (Santa Clara)"], ["−90%", "retrabalho (Ducks)"], ["−96%", "deslocamento (Sol e Ondas)"]],
    empresas: [
      { n: "Santa Clara", s: "Araxá", g: 6725160, x: true, r: "−99,1% de refugo, +85% de produtividade" },
      { n: "Fertitrading", s: "Fertilizantes · Araxá", g: 1910000, r: "−50% de deslocamento, +20% de produtividade" },
      { n: "Marabá", s: "Patos de Minas", g: 1120000, r: "−83% de deslocamento, 2 pessoas realocadas" },
      { n: "Sol e Ondas", s: "Patos de Minas", g: 810000, r: "−96% de deslocamento, +50% de produtividade" },
      { n: "Serya", s: "Araxá", g: 481000, r: "−80% de horas extras, −47% de custos diretos" },
      { n: "PDCA", s: "Uberlândia", g: 219972, r: "−90% de horas extras" },
      { n: "Flexcon", s: "Patos de Minas", g: 48000, r: "−50% de custos diretos" },
      { n: "Destilaria Rio do Cachimbo", s: "Patos de Minas", g: 42000, r: "5S em 77% e 90 m² liberados" },
      { n: "Ducks", s: "Patos de Minas", r: "−90% de retrabalho" },
    ],
    fotos: [],
  },
  {
    id: "lean-construction-2018",
    nome: "Lean Construction · Uberlândia e Uberaba",
    ano: 2018, anoLabel: "2017–2018",
    parceiro: "PROCOMPI · FIEMG",
    local: "Uberlândia e Uberaba (MG)",
    cidades: ["Uberlândia", "Uberaba"],
    setores: ["con"],
    e: 16,
    resumo: "Dezesseis construtoras e incorporadoras levaram o Lean ao canteiro, de novembro de 2017 a maio de 2018: estudo de passos, controle de almoxarifado, traço de argamassa e cronograma.",
    kpis: [["−97%", "deslocamento no canteiro (Pittelli)"], ["57% → 0%", "desvio de estoque (HPR)"], ["4 meses", "de antecipação de obra (Dakarsa)"]],
    empresas: [
      { n: "Cincol Construtora", g: 1340000, r: "−30% de mão de obra direta, +20% de produtividade em alvenaria e reboco" },
      { n: "TCENCO", g: 1139400, r: "−15% de custos diretos, 40% da mão de obra otimizada" },
      { n: "RCG", g: 236000, r: "−80% de deslocamento na confecção de lajes, −34% de ociosidade" },
      { n: "HPR Construtora", g: 164000, r: "Desvio de estoque de 57% para 0%, −78% em locação de máquinas" },
      { n: "Pittelli Engenharia", g: 75300, r: "Container de cimento ao lado da betoneira: de 39 passos para 1 por viagem" },
      { n: "Nunes e Nunes", r: "−44% de argamassa, −33% de matéria-prima" },
      { n: "Canassa", r: "−53,6% de atraso de obra" },
      { n: "Dakarsa", r: "Obra entregue 4 meses antes do previsto" },
      { n: "Ribeiro e Ribeiro", r: "+44% de vendas" },
    ],
    fotos: [],
  },
  {
    id: "refrigeracao-2018",
    nome: "Lean na Refrigeração",
    ano: 2018, anoLabel: "2018",
    parceiro: "SEBRAE",
    local: "Setor de refrigeração e climatização",
    cidades: [],
    setores: ["ser"],
    e: 2,
    resumo: "Turma setorial com empresas de instalação e manutenção de refrigeração.",
    kpis: [["−84%", "NVAA em set-up (Apolo)"], ["+60%", "faturamento (Reclimar)"]],
    empresas: [
      { n: "Apolo", g: 263000, r: "−84% de NVAA em set-up e paradas, −50% de horas ociosas" },
      { n: "Reclimar", g: 96294, r: "+60% de faturamento" },
    ],
    fotos: [],
  },
  {
    id: "itajuba-2019",
    nome: "PROCOMPI · Itajubá",
    ano: 2019, anoLabel: "2018–2019",
    parceiro: "PROCOMPI · FIEMG · SIMMMEI",
    local: "Itajubá, Sul de Minas (MG)",
    cidades: ["Itajubá"],
    setores: ["ind"],
    e: 5,
    resumo: "Ferramentarias e usinagens do Sul de Minas, de julho de 2018 a fevereiro de 2019. Uma delas desenvolveu um software de programação CNC no conceito Indústria 4.0.",
    kpis: [["−80%", "set-up do torno CNC (RCS)"], ["+60%", "OEE (RCS)"], ["2.780 h", "de máquina liberadas por ano"]],
    empresas: [
      { n: "GIMA Máquinas", g: 1440178, r: "+80% de OEE, −43% de NVAA, 100% de reaproveitamento do estoque" },
      { n: "RCS Usinagem", bc: 104.45, r: "Programação + set-up de 3,5 h para 45 min, refugo de try-out zerado" },
      { n: "Erominas", g: 630000, p: true, r: "+30% de produtividade e de disponibilidade de máquina" },
      { n: "GNS", r: "Deslocamento de 532 para 260 m/dia, NVAA de 73% para 45%" },
      { n: "Invent Automação", r: "+30% de produtividade, −30% de set-up" },
    ],
    fotos: ["rcs-ferramentas", "rcs-bancada"],
  },
  {
    id: "patos-2019",
    nome: "PROCOMPI · Patos de Minas",
    ano: 2019, anoLabel: "2019",
    parceiro: "PROCOMPI · FIEMG",
    local: "Patos de Minas (MG)",
    cidades: ["Patos de Minas"],
    setores: ["ind", "ofi"],
    e: 14,
    resumo: "Catorze empresas do Alto Paranaíba, metade delas oficinas de caminhões e distribuidoras de peças. Na maioria, o payback veio em menos de um mês.",
    kpis: [["R$ 13 mi", "ganho líquido anual"], ["521×", "benefício/custo (Volksdiesel)"], ["< 1 mês", "payback em 10 de 11 empresas"]],
    empresas: [
      { n: "Oficina do Baiano", s: "Reparação de veículos pesados", g: 3359960, bc: 178, r: "+150% de produtividade" },
      { n: "Aço Fort", g: 3099400, bc: 14.1, r: "Produtividade dobrada, −85% de NVAA" },
      { n: "Trucks Hélio", g: 2050000, bc: 70.2, r: "−50% de NVAA e de horas extras" },
      { n: "Diferpam", g: 1005600, bc: 32.3, r: "+85% de performance, +36% de produtividade" },
      { n: "Motocarga", g: 797664, bc: 122, r: "−90% de NVAA, +42% de produtividade" },
      { n: "Volksdiesel", g: 675000, bc: 521, r: "−85% de NVAA, +44% de produtividade, −50% de horas extras" },
      { n: "Dicave · JD Peças", g: 632973, bc: 37, r: "−75% de NVAA" },
      { n: "Reformas Vieira", g: 599000, r: "−50% de estoque" },
      { n: "Aço Fama", g: 304500, bc: 5.95, r: "−90% de NVAA, +62% de produtividade, payback em 2 meses" },
      { n: "Trucks Alair", g: 249000, bc: 250, r: "Estoque reorganizado e 5S implantado" },
      { n: "Dante Molas", g: 230300, bc: 24.7, r: "−20% de estoque" },
      { n: "Acinox" }, { n: "Empa" }, { n: "Recalto" },
    ],
    fotos: [],
  },
  {
    id: "multibag-2024",
    nome: "Consultoria direta · Multibag",
    ano: 2024, anoLabel: "2024",
    parceiro: "Cliente privado",
    local: "Indústria de big bags",
    cidades: [],
    setores: ["ind"],
    e: 1,
    resumo: "Acompanhamento mensal de indicadores com a diretoria: produção, absenteísmo, eficiência e planejamento.",
    kpis: [["+18%", "produção média diária"], ["+17,6%", "faturamento médio mensal"], ["2,5 → <1", "mês de planejamento"]],
    empresas: [{ n: "Multibag", r: "Produção diária 18% maior que em 2023, planejamento de 2,5 meses para menos de um" }],
    fotos: [],
  },
];

/* Outros trabalhos citados nas apresentações, sem números consolidados. */
window.AG_OTHERS = [
  { nome: "Prefeitura de Betim · Programa Cesta Escola", setor: "pub", cidade: "Betim", nota: "Lean na gestão pública: descentralização do atendimento para reduzir a espera dos beneficiários." },
  { nome: "Lean Garage Pernambuco", setor: "ofi", cidade: "Recife", nota: "Programa de melhoria contínua para oficinas em Pernambuco." },
  { nome: "Reparação automotiva · ES e RJ", setor: "ofi", cidade: "Cariacica", nota: "Oficinas em Cariacica, Cachoeiro de Itapemirim e Duque de Caxias." },
];

/* Pares de antes e depois, todos com o mesmo recorte e o mesmo tratamento. */
window.AG_PAIRS = {
  "delta-usinagem": { emp: "Delta Industrial", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Centro de usinagem", txt: "Faixas no piso, carrinho de ferramentas no ponto de uso e o caminho do operador livre.", kpi: "−95% de NVAA" },
  "delta-fresa": { emp: "Delta Industrial", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Fresadora", txt: "Painel de ferramentas na parede e área demarcada em volta da máquina.", kpi: "B/C 29×" },
  "lavanderia-galpao": { emp: "Lavanderia Santo Antônio", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Galpão de lavagem", txt: "Roupa fora do chão, bancadas alinhadas e fluxo da recepção à calandra.", kpi: "Calandra de 5 para 3 pessoas" },
  "suporte-bancada": { emp: "Suporte Automação", lugar: "Matozinhos", prog: "bh-lafaiete-2014", titulo: "Bancada de montagem", txt: "Gaveteiros identificados e a bancada liberada para o trabalho.", kpi: "B/C 12×" },
  "suporte-fixadores": { emp: "Suporte Automação", lugar: "Matozinhos", prog: "bh-lafaiete-2014", titulo: "Estoque de fixadores", txt: "Caixas azuis por tipo de parafuso e terminal, à vista de quem monta.", kpi: "Busca por peça eliminada" },
  "visual-fachada": { emp: "Visual Propaganda", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Fachada e recepção", txt: "A empresa saiu do improviso e ganhou uma entrada que conta o que ela faz.", kpi: "−69% de deslocamento" },
  "visual-galpao": { emp: "Visual Propaganda", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Galpão de produção", txt: "Mais de 110 m² liberados com novo layout e fluxo de materiais.", kpi: "+110 m²" },
  "dablius-patio": { emp: "Dablius Industrial", lugar: "Conselheiro Lafaiete", prog: "bh-lafaiete-2014", titulo: "Pátio de sobras", txt: "Sucata e paletes viraram um estoque de sobras demarcado e inventariado.", kpi: "Estoque sob controle" },
  "metaltecnica-producao": { emp: "Metaltécnica", lugar: "João Monlevade", prog: "monlevade-2015", titulo: "Caldeiraria", txt: "Fluxo refeito em sequência: preparação, montagem leve, pesada, solda e acabamento.", kpi: "−60% de movimentação" },
  "qualictec-galpao": { emp: "Qualictec", lugar: "João Monlevade", prog: "monlevade-2015", titulo: "Área de recuperação", txt: "Sucata retirada, piso recuperado e espaço preparado para uma sala de treinamento.", kpi: "−40% de horas perdidas" },
  "isotec-bancada": { emp: "Isotec", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Bancada de calibração", txt: "Do canto escuro com peças soltas para uma sala limpa e padronizada.", kpi: "Posto de trabalho padronizado" },
  "rcs-ferramentas": { emp: "RCS Usinagem", lugar: "Itajubá", prog: "itajuba-2019", titulo: "Gaveta de ferramentas", txt: "Cada ferramenta com lugar definido. O set-up do torno caiu de 2 horas para 30 minutos.", kpi: "−80% de set-up" },
  "jw-almox": { emp: "JW Manutenções", lugar: "João Monlevade", prog: "monlevade-2015", titulo: "Almoxarifado", txt: "Peças de talhas separadas por tipo, com paleteira e corredor livre.", kpi: "−78% de deslocamento" },
  "causimec-ferramentaria": { emp: "Causimec", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Ferramentaria", txt: "Escaninhos identificados e painel de ferramentas no ponto de uso.", kpi: "Busca por ferramenta eliminada" },
  "metaltecnica-almox": { emp: "Metaltécnica", lugar: "João Monlevade", prog: "monlevade-2015", titulo: "Almoxarifado", txt: "Prateleiras por família de item e caixas identificadas.", kpi: "460 m² liberados" },
  "tetum-obra": { emp: "Tetum Engenharia", lugar: "Patos de Minas", prog: "procompi-2017", titulo: "Canteiro de obra", txt: "5S e controle de obra no edifício-sede de uma cooperativa de crédito.", kpi: "+60% de performance" },
  "visual-corredor": { emp: "Visual Propaganda", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Corredor lateral", txt: "O corredor que guardava sobras virou passagem livre.", kpi: "Área recuperada" },
  "precisa-oficina": { emp: "Balanças Precisa", lugar: "Belo Horizonte", prog: "bh-lafaiete-2014", titulo: "Oficina de balanças", txt: "Empilhadeira e caixas fora do caminho, chão demarcado.", kpi: "Fluxo desobstruído" },
  "rcs-bancada": { emp: "RCS Usinagem", lugar: "Itajubá", prog: "itajuba-2019", titulo: "Centro de usinagem", txt: "Armário de ferramentas ao lado da máquina e posto limpo.", kpi: "+60% de OEE" },
};

/* Ordem curada da galeria. */
window.AG_GALLERY = ["visual-fachada", "delta-usinagem", "lavanderia-galpao", "metaltecnica-producao", "suporte-bancada", "qualictec-galpao", "dablius-patio", "isotec-bancada", "rcs-ferramentas", "delta-fresa", "jw-almox", "visual-galpao", "causimec-ferramentaria", "suporte-fixadores", "tetum-obra"];

window.AG_TOOLS = [
  ["5S", "Organização", "Senso de utilização, ordem, limpeza, padronização e disciplina. A base de tudo que vem depois."],
  ["VSM", "Diagnóstico", "Mapa do fluxo de valor: do pedido à entrega, onde o tempo é gasto e onde ele é perdido."],
  ["NVAA", "Diagnóstico", "Atividade que não agrega valor. Cronoanálise separa o que o cliente paga do que é desperdício."],
  ["Spaghetti", "Diagnóstico", "Desenho dos passos reais do operador. Na Pittelli, 39 passos viraram 1."],
  ["SMED", "Fluxo", "Troca rápida de ferramenta. Na RCS, o set-up do torno CNC caiu de 2 h para 30 min."],
  ["Kaizen", "Melhoria", "Projetos curtos e focados na maior perda, conduzidos pela própria equipe da empresa."],
  ["5 Porquês", "Causa raiz", "Perguntar por que até chegar na causa que, removida, faz o problema não voltar."],
  ["4M", "Causa raiz", "Método, máquina, mão de obra e material: o diagrama de Ishikawa aplicado ao chão."],
  ["Poka-Yoke", "Qualidade", "Dispositivo à prova de erro: a peça errada não entra, o defeito não passa."],
  ["OEE", "Medição", "Disponibilidade × performance × qualidade. Uma linha de refrigeradores chegou a 77,2%."],
  ["TPM", "Manutenção", "Manutenção autônoma e profissional para a máquina parar por plano, não por quebra."],
  ["Kanban", "Fluxo", "Produção puxada pelo consumo. Na Metaldavi, um lote de 10 dias passou a sair em 3,9 h."],
  ["5W2H", "Gestão", "O quê, por quê, onde, quando, quem, como e quanto: o plano de ação que tem dono e prazo."],
  ["Muri · Mura", "Ergonomia", "Sobrecarga e irregularidade. Postos ajustados à altura do operador e carga balanceada."],
  ["SOP", "Padrão", "Procedimento operacional padrão: o melhor jeito conhecido, escrito e treinado."],
  ["B/C", "Resultado", "Benefício sobre custo. Todo projeto termina com o ganho anual medido e o payback calculado."],
];

window.AG_TIMELINE = [
  { ano: "1996", t: "Fiat · Betim", d: "Líder de equipe na linha de produção." },
  { ano: "1998", t: "Stola do Brasil", d: "Da funilaria à metodologia WCM: logística, melhoria focada e posto de trabalho." },
  { ano: "2010", t: "Academia Lean Fiat", d: "Certificado e padrinho de grupo de fornecedores da Fiat." },
  { ano: "2011", t: "Instrutor na Stola", d: "Forma líderes no Sistema de Produção Stola e lidera projetos." },
  { ano: "2012", t: "Consultoria própria", d: "Funda a Albert Gil Lean Consulting e lidera o 5S da Stola." },
  { ano: "2013", t: "Fiat, CNH e ABDI", d: "Instrutor de fornecedores Fiat/CNH e consultor de 10 empresas no FOCEM." },
  { ano: "2014", t: "SEBRAE em escala", d: "Turmas em MG e RJ até 2019, de oficinas a laticínios." },
  { ano: "2022", t: "Mikro-Stamp", d: "Diretor industrial em Campinas." },
  { ano: "2024", t: "GW Metal", d: "Diretor operacional em Limeira, dez áreas." },
  { ano: "2026", t: "LeanOS", d: "Software para o ganho não regredir." },
];

window.AG_QUOTES = [
  { q: "A presença do FOCEM na pessoa do Albert nos fez dar um salto rumo à competitividade. Foi um divisor de águas na empresa, tanto que já conquistamos um novo cliente, a Iveco.", who: "Adriano Dantas", ctx: "Engenheiro · Alumec, Diadema · 2014" },
  { q: "Tive que rever meus conceitos com o passar dos conhecimentos do consultor Albert Gil, que com paciência e boa educação nos fez envolver no projeto e apaixonar por esta metodologia.", who: "Carlos Eduardo", ctx: "Engenheiro · MRS, Mauá · 2014" },
  { q: "O Sr. Albert Gil nos mostrou o potencial que tínhamos. Hoje consideramos o Albert parte da família Jodeclan.", who: "Iran Braga", ctx: "Sócio · Jodeclan, São Bernardo do Campo · 2014" },
  { q: "Hoje conseguimos dar um passo importante rumo à melhoria contínua, muito devido aos conhecimentos compartilhados pelo consultor Albert Gil.", who: "Cláudia Matos", ctx: "Gerente de manufatura · Overdrill, Diadema · 2014" },
  { q: "Agradecemos ao Albert por ter passado todo seu conhecimento e estar sempre à disposição para esclarecer as dúvidas. Agora é conosco, sempre dispostos a buscar a melhoria contínua.", who: "Erominas", ctx: "PROCOMPI Itajubá · 2019" },
  { q: "Sou cliente do Graal Embaixador há 14 anos. De uns meses para cá, tenho observado um ar de renovação nos pratos, tanto na parte visual quanto no sabor.", who: "Vinícius Maranhão", ctx: "Cliente · Restaurante Graal Embaixador · 2016" },
];
